src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Federation Partner</fullName>
                </value>
                <value>
                    <fullName>Global System Integrator</fullName>
                </value>
                <value>
                    <fullName>Outbound OEM/ISV</fullName>
                </value>
                <value>
                    <fullName>Consulting Partner</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Technology Alliance</fullName>
                </value>
                <value>
                    <fullName>VAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Certification__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Product_Version__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Product Version</label>
        <referenceTo>Partner_Product_Version__c</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pivotal_Product_Version__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pivotal Product Version</label>
        <referenceTo>Pivotal_Integrated_Product_Version__c</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Record of a Partner's certification.</description>
    <label>Certification</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account to which the integrable product belongs.</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Product</relationshipLabel>
        <relationshipName>Partner_Product</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Business Continuity</fullName>
                </value>
                <value>
                    <fullName>Business Intelligence</fullName>
                </value>
                <value>
                    <fullName>Cloud Service Provider</fullName>
                </value>
                <value>
                    <fullName>Data Integration</fullName>
                </value>
                <value>
                    <fullName>Data Modeling</fullName>
                </value>
                <value>
                    <fullName>Database Tools</fullName>
                </value>
                <value>
                    <fullName>Deployment/Monitoring</fullName>
                </value>
                <value>
                    <fullName>Platform/Manageability</fullName>
                </value>
                <value>
                    <fullName>Search</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to keep track of all products (both Pivotal's and Partner's) that interoperate with other products.</description>
    <label>Partner Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Product_Version__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name_Partner__c</fullName>
        <label>Product Name</label>
        <referenceTo>Partner_Product__c</referenceTo>
        <relationshipLabel>Product Versions</relationshipLabel>
        <relationshipName>Partner_Product_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Tracks the versions of a product</description>
    <label>Partner Product Version</label>
    <nameField>
        <label>Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Product Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pivotal_Integrated_Product__c.object
<CustomObject>
    <description>Pivotal products that have been/are capable of integrated with other products.</description>
    <label>Pivotal Integrated Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pivotal Integrated Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pivotal_Integrated_Product_Version__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name_Piv__c</fullName>
        <label>Product Name</label>
        <referenceTo>Pivotal_Integrated_Product__c</referenceTo>
        <relationshipLabel>Product Versions</relationshipLabel>
        <relationshipName>Pivotal_Integrated_Product_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pivotal Integrated Product Version</label>
    <nameField>
        <label>Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pivotal Integrated Product Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/autocompleteControllerTests.cls
@isTest(seeAllData=true)
public class autocompleteControllerTests {

    private static void createTestData() {
        //Insert Pivotal Integrated Product data
        Pivotal_Integrated_Product__c pivprod1 = new Pivotal_Integrated_Product__c(Name='GPDB'); 
        Pivotal_Integrated_Product__c pivprod2 = new Pivotal_Integrated_Product__c(Name='GPHD'); 
        insert pivprod1;
        insert pivprod2;
        
        //Insert Pivotal Integrated Product Versions

        Pivotal_Integrated_Product_Version__c pivver1 = new Pivotal_Integrated_Product_Version__c(Name='4.0', Product_Name_Piv__c=pivprod1.Id);
        Pivotal_Integrated_Product_Version__c pivver2 = new Pivotal_Integrated_Product_Version__c(Name='4.1', Product_Name_Piv__c=pivprod1.Id);
        Pivotal_Integrated_Product_Version__c pivver3 = new Pivotal_Integrated_Product_Version__c(Name='3.0', Product_Name_Piv__c=pivprod2.Id);
        Pivotal_Integrated_Product_Version__c pivver4 = new Pivotal_Integrated_Product_Version__c(Name='3.1', Product_Name_Piv__c=pivprod2.Id);
        insert pivver1;
        insert pivver2;
        insert pivver3;
        insert pivver4;

        //Insert some Partner Accounts
        Account alpine = new Account(Name='Alpine Data Labs', Type='Partner', Partner_Type__c = 'Technology Alliance');
        Account tableau = new Account(Name='Tableau', Type='Partner', Partner_Type__c = 'Technology Alliance');
        insert alpine;
        insert tableau;

        //Insert Partner Products
        Partner_Product__c partprod1 = new Partner_Product__c(Name='Alpine Illuminator', Account__c=alpine.Id, Product_Category__c = 'Analytics');
        Partner_Product__c partprod2 = new Partner_Product__c(Name='Tableau Desktop', Account__c=tableau.Id, Product_Category__c = 'Analytics');
        Partner_Product__c partprod3 = new Partner_Product__c(Name='Alpine Miner', Account__c=alpine.Id, Product_Category__c = 'Analytics');
        Partner_Product__c partprod4 = new Partner_Product__c(Name='Alpine Studio', Account__c=alpine.Id, Product_Category__c = 'Analytics');
        insert partprod1;
        insert partprod2;
        insert partprod3;
        insert partprod4;

        // Insert Partner Product Versions
        Partner_Product_Version__c partver1 = new Partner_Product_Version__c(Name='2.7', Product_Name_Partner__c = partprod1.Id); //Alpine Illuminator 2.7
        Partner_Product_Version__c partver2 = new Partner_Product_Version__c(Name='2.8', Product_Name_Partner__c = partprod1.Id); //Alpine Illuminator 2.8
        Partner_Product_Version__c partver3 = new Partner_Product_Version__c(Name='8.0', Product_Name_Partner__c = partprod2.Id); //Tableau Desktop 8.0
        Partner_Product_Version__c partver4 = new Partner_Product_Version__c(Name='8.1', Product_Name_Partner__c = partprod2.Id); //Tableau Desktop 8.1
        Partner_Product_Version__c partver5 = new Partner_Product_Version__c(Name='3.6', Product_Name_Partner__c = partprod3.Id); //Alpine Miner 3.6
        Partner_Product_Version__c partver6 = new Partner_Product_Version__c(Name='3.7', Product_Name_Partner__c = partprod3.Id); //Alpine Miner 3.7
        Partner_Product_Version__c partver7 = new Partner_Product_Version__c(Name='4.4', Product_Name_Partner__c = partprod4.Id); //Alpine Studio 4.4
        
        //Insert
        insert partver1;
        insert partver2;
        insert partver3;
        insert partver4;
        insert partver5;
        insert partver6;
        insert partver7;        
        
        //Create some certifications
        Certification__c cert1 = new Certification__C(Pivotal_Product_Version__c=pivver1.Id, Partner_Product_Version__c=partver1.Id, Status__c='Completed'); //GPDB 4.0 - Alpine Illuminator 2.7
        Certification__c cert2 = new Certification__C(Pivotal_Product_Version__c=pivver1.Id, Partner_Product_Version__c=partver2.Id, Status__c='Completed'); //GPDB 4.0 - Alpine Illuminator 2.8
        Certification__c cert3 = new Certification__C(Pivotal_Product_Version__c=pivver2.Id, Partner_Product_Version__c=partver1.Id, Status__c='Completed'); //GPDB 4.1 - Alpine Illuminator 2.7
        Certification__c cert4 = new Certification__C(Pivotal_Product_Version__c=pivver2.Id, Partner_Product_Version__c=partver2.Id, Status__c='Completed'); //GPDB 4.1 - Alpine Illuminator 2.8
        Certification__c cert5 = new Certification__C(Pivotal_Product_Version__c=pivver1.Id, Partner_Product_Version__c=partver3.Id, Status__c='Completed'); //GPDB 4.0 - Tableau Desktop 8.0
        Certification__c cert6 = new Certification__C(Pivotal_Product_Version__c=pivver2.Id, Partner_Product_Version__c=partver3.Id, Status__c='Completed'); //GPDB 4.1 - Tableau Desktop 8.0
        insert cert1;
        insert cert2;
        insert cert3;
        insert cert4;
        insert cert5;
        insert cert6;

    }      
    
    static testMethod void testSearchObjectmethod() {
        createTestData();
        //object is valid object to search
        List<sObject> results = AutocompleteController.searchObject('Partner_Product__c', 'alp', '10', 'true');
        List<sObject> expected = [ 	SELECT id, Name 
                                  	FROM Partner_Product__c
                                	WHERE Name LIKE '%alp%'
                                 	ORDER BY Name
                                 	LIMIT 10];
        System.assertEquals(expected, results);
        
        //object is not a valid object to search
        results = AutocompleteController.searchObject('Partner_And_Pivotal_Product__c', 'alp', '10', 'true');
        System.assertEquals(null, results);
        
        //catch QueryException
        results = AutocompleteController.searchObject('Partner_Product__c', 'alp', '-1', 'true');
        System.assertEquals(null, results);
        
    }
    
    
}