src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Special_Handling__c</fullName>
        <description>Pivotal tracker #[121533025] : EHSP desgination/rules on Account</description>
        <inlineHelpText>Identifies customers requesting Special Handling regarding their identity and data. This includes Federal Government or commercial entities that require specific processes and personnel for management of their support tickets.</inlineHelpText>
        <label>Special Handling</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>EH - Executive Handling</fullName>
                </value>
                <value>
                    <fullName>SP - Special Practices</fullName>
                </value>
                <value>
                    <fullName>EU - Safe Harbour</fullName>
                </value>
                <value>
                    <fullName>EU - Global Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Handling_Instructions__c</fullName>
        <description>This field will display will display Handling Instructions on case</description>
        <label>Handling Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Special_Handling_Type__c</fullName>
        <label>Special Handling Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EU - Safe Harbour</fullName>
                </value>
                <value>
                    <fullName>Executive Handling (Non-BRICE)</fullName>
                </value>
                <value>
                    <fullName>Special Practices (US Citizen, US Soil)</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Handling__c</fullName>
        <formula>IF( ISPICKVAL(Account.Special_Handling__c,'EH - Executive Handling') ,'Executive Handling (Non-BRICE)',
 IF( ISPICKVAL(Account.Special_Handling__c,'SP - Special Practices') ,'Special Practices (US Citizen, US Soil)',
IF( ISPICKVAL(Account.Special_Handling__c,'EU - Safe Harbour') ,'EU - Safe Harbour',
 IF(ISPICKVAL( Account.Special_Handling__c ,'Standard') , 'Standard', 
NULL))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Special Handling</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Handling_Instructions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Special_Handling_Instructions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Handling_Instructions__c</fullName>
        <description>This field will have Handling Instructions</description>
        <label>Handling Instructions</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <description>This object is used to display Special Handling Instructions</description>
    <label>Handling Instructions</label>
    <nameField>
        <label>Special Handling Instructions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Handling Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/classes/PS_SpecialHandlingTriggerhandler_TC.cls
@isTest
public class PS_SpecialHandlingTriggerhandler_TC{
static testMethod void  specialHandlingTriggerhandler()
    {
         TestDataUtil.dataValueMapCSData();
         account accobj= new Account();
         accobj.name ='Test123';
         accobj.Special_Handling__c = 'Standard';
         insert accobj;
         system.debug('Account Created' +  accobj);
         Map<Id,account> accountMap = new Map<Id,account>();
         accountMap.put(accobj.id,accobj);
         system.debug('accountMap' +  accountMap);
         system.debug('accobj.id' +  accobj.id);
         accobj.Special_Handling__c = 'EH - Executive Handling';
         system.debug('accountMap' +  accountMap);
         system.debug('accobj.id' +  accobj.id);
        
         list<case>caseupdate= new list<Case>();       
        
        case cobj =new case();
         cobj.Special_Handling_Instructions__c ='test';
         cobj.Products__c='Datometry Hyper-Q for Pivotal Data Suite';
         cobj.AccountId=accobj.id;
         cobj.subject='TS-34';
         cobj.description='TS-34 : Test SS';
         insert cobj;
         system.debug('Case Created' +  cobj);
         system.debug('cobj.AccountId ' +  cobj.AccountId);
         
         Special_Handling_Instructions__c  sp =new Special_Handling_Instructions__c();
         sp.Handling_Instructions__c='test12';
         sp.Products__c='Datometry Hyper-Q for Pivotal Data Suite';
         sp.Account__c=accobj.id;
         insert sp;
         
         
        
         if(accountMap.containskey(cobj.AccountId)){
         system.debug('inside if ' +  cobj.AccountId);
         cobj.Special_Handling_Type__c  = accountMap.get(cobj.AccountId).Special_Handling__c;
         system.debug('cobj.Special_Handling_Type__c ' + cobj.Special_Handling_Type__c);
         system.debug('accountMap.get(cobj.accountId).Special_Handling__c ' + accountMap.get(cobj.accountId).Special_Handling__c);
    
        system.debug('Inserted');
         if(sp.account__c==cobj.AccountId && cobj.Products__c==sp.Products__c)
                {
                  
                    cobj.Special_Handling_Instructions__c=sp.Handling_Instructions__c;
                    system.debug('cobj.Special_Handling_Instructions__c' + cobj.Special_Handling_Instructions__c);
                    system.debug('sp.Handling_Instructions__c' + sp.Handling_Instructions__c);
                    update cobj;
                    }
                    /*  if(cobj.Products__c==spl.Products__c)
                    {
                    cobj.Special_Handling_Instructions__c=spl.Handling_Instructions__c;
                    system.debug('cobj.Special_Handling_Instructions__c' + cobj.Special_Handling_Instructions__c);
                    system.debug('sp.Handling_Instructions__c' + sp.Handling_Instructions__c);
                    update cobj;
                    }
                    }*/
                }  
        system.debug('After If');

         update accobj;
         update sp;
         //update spl;
         update cobj;
        
    }
}