src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes_from_Compliance_Team__c</fullName>
        <inlineHelpText>This field will be filled by Compliance team for flagged/blocked accounts</inlineHelpText>
        <label>Notes from Compliance Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RPS_Status__c</fullName>
        <defaultValue>"Pending"</defaultValue>
        <description>RPS Screening Status in Visual Compliance [PT #126414043]</description>
        <inlineHelpText>RPS Screening Status in Visual Compliance</inlineHelpText>
        <label>RPS Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Cleared_by_Compliance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cleared by Compliance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will Be Used to select key point contact</description>
        <label>Add / Manage Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Portal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To enable contact as the community user</inlineHelpText>
        <label>Open Cases for Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes_From_Compliance_Team__c</fullName>
        <label>Notes From Compliance Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RPS_Status__c</fullName>
        <defaultValue>"Pending"</defaultValue>
        <label>RPS Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Account_Cases__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View all Cases for Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataValueMap__c.object
<CustomObject>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This cs is used to hold all the data value required to customize functionality</description>
    <label>Data Value Map</label>
</CustomObject>

src/objects/PortalObjectAccess__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <defaultValue>"Read"</defaultValue>
        <inlineHelpText>Read 
Edit</inlineHelpText>
        <label>Shared Account</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <defaultValue>"Read"</defaultValue>
        <inlineHelpText>Read 
Edit</inlineHelpText>
        <label>Shared Account's Case</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <defaultValue>"Read"</defaultValue>
        <inlineHelpText>Read 
Edit</inlineHelpText>
        <label>Shared Account's Contact</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <defaultValue>"Read"</defaultValue>
        <label>Shared Account's Opportunity</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>PortalObjectAccess</label>
</CustomObject>

src/classes/AccountHelper.cls
/*******************************************************************************************************************
* Apex Class Name  : AccountHelper 
* Test Class Name  : AccountHelper_TC
* Version          : 1.0
* Function         : 
* Modification Log :
*
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Amit                        09/22/2017              intial version
* --------------------------------------------------------------------------------------------------------------------
*******************************************************************************************************************/
public without Sharing class AccountHelper {
    public account acc; 
/***
Method Name : AccountHelper
Purpose : Constructor
***/    
    public AccountHelper( ApexPages.StandardController stdController ){
        acc = (account)stdController.getRecord();        
    }
/***    
Method Name : rollupOppContacts
Purpose : Used to roll up Account access
***/
    public void rollupOppContacts(){
        AccountHelper.rollupAccountAccess(acc.Id );   
    }
    
/***
Method Name : rollupAccountAccess
Purpose : Used to roll up Account access
***/
    public static void rollupAccountAccess(Id accId){
        Datetime sysTime = System.now();
        sysTime = sysTime.addSeconds(-10);
        List<accountContactRole> contactRoleRec = [SELECT ContactId,Role,Contact.AccountID,Contact.Customer_Admin__c,Contact.View_Account_Cases__c,Contact.Enable_Portal_User__c ,lastModifiedDate, isDeleted FROM accountContactRole WHERE accountId =: accId and lastModifiedDate >: sysTime and contact.AccountID !=:accId Order By lastModifiedDate asc limit 1 ALL ROWS];
        
        if(!contactRoleRec.isEmpty()){
            List<Contact> contactToUpdate = new List<contact>();
            Map<String,PortalObjectAccess__c> portalObjectAccessMap = PortalObjectAccess__c.getAll();
            Map<Id,AccountContactRole> mapAccountContactRole = new Map<Id,AccountContactRole>();            
            for(accountContactRole acR : contactRoleRec){
                mapAccountContactRole.put(acR.ContactID,acR);
            }
            if(!portalObjectAccessMap.isEmpty()){                
                Map<Id,AccountContactRole> userIds = new Map<Id,AccountContactRole>();
                Map<Id,User> userTobeRemovedMap = new Map<Id,User>();
                Map<Id,portalObjectAccess__c> userToUpsertMap = new Map<Id,portalObjectAccess__c>();
                List<AccountShare> accShareToCreate = new List<AccountShare>();                
                for(User usr :[SELECT Id,isActive,ProfileId,ContactID,AccountId FROM user WHERE contactID =:mapAccountContactRole.KeySet()]){
                    AccountContactRole acR = mapAccountContactRole.get(usr.ContactID);                    
                    if(acR.isDeleted){
                        userTobeRemovedMap.put(usr.Id,usr);
                        userIds.put(usr.id,acR);
                    }else{
                        String contactRole = String.ValueOf(acR.Role).remove('-');
                        String key = usr.ProfileId+ContactRole.deleteWhitespace();
                        System.debug('key ---->'+key );
                        portalObjectAccess__c objAccess = portalObjectAccessMap.get(key);
                        System.debug('objAccess ---->'+objAccess );
                        if(objAccess != null){
                            AccountShare accShare = new AccountShare();
                            accShare.AccountAccessLevel = objAccess.Account__c;
                            accShare.ContactAccessLevel= objAccess.Contact__c;
                            accShare.CaseAccessLevel= objAccess.Case__c;
                            accShare.OpportunityAccessLevel= objAccess.Opportunity__c;
                            accShare.AccountId = accId;
                            accShare.Userorgroupid = usr.id;
                            accShareToCreate.add(accShare);
                            userIds.put(usr.id,acR);
                            userToUpsertMap.put(usr.Id, objAccess);
                        }
                    }
                }
                
                List<AccountShare> accShareToUpdate = new List<AccountShare>();
                List<AccountShare> accShareToDelete = new List<AccountShare>();
                Boolean isShareexists = false;
                for(AccountShare accShare :[SELECT Id,AccountId, AccountAccessLevel,UserOrGroupId,ContactAccessLevel,CaseAccessLevel FROM AccountShare WHERE AccountId =: accId and UserOrGroupId =:userIds.KeySet()]){
                    Id usrId = accShare.UserOrGroupId;                    
                    if(userTobeRemovedMap.containsKey(usrId)){
                        isShareexists = true;
                        accShareToDelete.add(accShare);
                    }
                    if(userToUpsertMap.containsKey(usrId)){
                        portalObjectAccess__c objAccess = userToUpsertMap.get(usrId);
                        String shareKey = accShare.AccountAccessLevel+accShare.ContactAccessLevel+accShare.CaseAccessLevel;
                        String masterKey = objAccess.Account__c+objAccess.Contact__c+objAccess.Case__c;
                        if(shareKey != masterKey){
                            isShareexists = true;
                            accShare.AccountAccessLevel = objAccess.Account__c;
                            accShare.ContactAccessLevel = objAccess.Contact__c;
                            accShare.CaseAccessLevel = objAccess.Case__c;
                            accShareToUpdate.add(accShare);
                        }                        
                    }
                }
                try{
                    if(isShareexists && !accShareToUpdate.isEmpty()){
                        update accShareToUpdate;
                    }                    
                    if(!accShareToDelete.isEmpty()){
                        delete accShareToDelete;
                    }
                    if(!isShareexists && !accShareToCreate.isEmpty()){
                        insert accShareToCreate;
                    }
                }
                Catch(Exception e){
                    ErrorLog.CreateER(e);//Exception captured in Utility Class Errorlog
                }
            }
        }
    }
/***
Method Name : UpdateCaseCommentOnContact
Purpose : To insert caseComment in case object
***/
   /* public static void UpdateCaseCommentOnContact(List<Contact> lstContact){
        set<ID> contactId = new set<ID>();
        set<ID> caseId = new set<ID>();
        
        List<FeedItem> lstFeedItem = new List<FeedItem>();
        String OnHold = DataValueMap__c.getInstance('On Hold').Data_Value__c;
        for(Contact con : lstContact){
            if(!con.Cleared_by_Compliance__c && String.isNotBlank(con.Notes_From_Compliance_Team__c) && (con.RPS_Status__c == 'red' || con.RPS_Status__c == 'yellow')){
                contactId.add(con.id);
            }
        }
        for(Contact con : [select id,(Select id,status from cases where status = :OnHold) from contact where id IN :contactId]){
            for(case cas : con.cases){
                caseId.add(cas.id);
            }
        }
        for(ID Feed : CaseId){
            feedItem fi = new FeedItem();
            fi.ParentId = Feed;
            fi.body = 'Contact not Cleared by Compliance';
            lstFeedItem.add(fi);
        }
        if(!lstFeedItem.isEmpty()){
            try{
                insert lstFeedItem;
            }
            Catch(Exception e){
                ErrorLog.CreateER(e);//Exception captured in Utility Class Errorlog
            }
        }
    } */
}