src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Special_Handling__c</fullName>
        <description>Pivotal tracker #[121533025] : EHSP desgination/rules on Account</description>
        <inlineHelpText>Identifies customers requesting Special Handling regarding their identity and data. This includes Federal Government or commercial entities that require specific processes and personnel for management of their support tickets.</inlineHelpText>
        <label>Special Handling</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>EH - Executive Handling</fullName>
                </value>
                <value>
                    <fullName>SP - Special Practices</fullName>
                </value>
                <value>
                    <fullName>EU - Safe Harbour</fullName>
                </value>
                <value>
                    <fullName>EU - Global Access</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comments__c</fullName>
        <label>Case Comments</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Products__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Component</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PoC</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>QA / Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Handling__c</fullName>
        <formula>IF( ISPICKVAL(Account.Special_Handling__c,'EH - Executive Handling') ,'Executive Handling (Non-BRICE)',
 IF( ISPICKVAL(Account.Special_Handling__c,'SP - Special Practices') ,'Special Practices (US Citizen, US Soil)',
IF( ISPICKVAL(Account.Special_Handling__c,'EU - Safe Harbour') ,'EU - Safe Harbour',
 IF(ISPICKVAL( Account.Special_Handling__c ,'Standard') , 'Standard', 
NULL))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Special Handling</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Technical</fullName>
        <active>true</active>
        <businessProcess>Pivotal Support</businessProcess>
        <label>Technical</label>
    </recordTypes>
</CustomObject>

src/objects/CaseDep__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <description>This field is used to store case component field value</description>
        <label>Component</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductVersion__c</fullName>
        <label>ProductVersion</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcomponent__c</fullName>
        <label>Subcomponent</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <description>This object is store case field dependent records</description>
    <label>CaseDep</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>CaseDepName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CaseDep</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will Be Used to select key point contact</description>
        <label>Add / Manage Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Portal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To enable contact as the community user</inlineHelpText>
        <label>Open Cases for Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interact_with_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Assign User L1 Profile Permissions</description>
        <inlineHelpText>Assign User L1 Profile Permissions</inlineHelpText>
        <label>Interact with Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View_Account_Cases__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View all Cases for Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataValueMap__c.object
<CustomObject>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This cs is used to hold all the data value required to customize functionality</description>
    <label>Data Value Map</label>
</CustomObject>

src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>ProductEntitlementMap__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>ProductEntitlementMap__c.SFDC_Product_Name__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ProductEntitlementMap__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_SKU__c</fullName>
        <formula>ProductEntitlementMap__r.Product_SKU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SKU Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductEntitlementMap__c.object
<CustomObject>
    <fields>
        <fullName>Entitlement_Process__c</fullName>
        <label>Entitlement Process</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_SKU__c</fullName>
        <label>Product SKU Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>SKU Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Product_Name__c</fullName>
        <label>SFDC Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>This object is used to store Product SKU's for Product Mapping for Automatic Entitlement Creation.</description>
    <label>Product Entitlement Map</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductEntitlementMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Component.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Access Control</fullName>
    </customValue>
    <customValue>
        <fullName>Ambari</fullName>
    </customValue>
    <customValue>
        <fullName>Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Apps ManagerV1</fullName>
        <label>Apps Manager</label>
    </customValue>
    <customValue>
        <fullName>AWS Service Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Azure Service Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Backup and Restore</fullName>
    </customValue>
    <customValue>
        <fullName>Blobstore</fullName>
    </customValue>
    <customValue>
        <fullName>BOSH (OSS)</fullName>
        <label>BOSH</label>
    </customValue>
    <customValue>
        <fullName>BOSH Backup &amp; Restore</fullName>
    </customValue>
    <customValue>
        <fullName>Buildpacks</fullName>
    </customValue>
    <customValue>
        <fullName>c2c Networking</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog &amp; Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog and Metadata</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog and Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog Brokers</fullName>
    </customValue>
    <customValue>
        <fullName>CF CLI</fullName>
    </customValue>
    <customValue>
        <fullName>CFCR</fullName>
    </customValue>
    <customValue>
        <fullName>ClamAV addon for PCF</fullName>
    </customValue>
    <customValue>
        <fullName>Client / Loading tools</fullName>
    </customValue>
    <customValue>
        <fullName>Client Access Methods</fullName>
    </customValue>
    <customValue>
        <fullName>Clients</fullName>
    </customValue>
    <customValue>
        <fullName>Client Tools</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Controller</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse</fullName>
    </customValue>
    <customValue>
        <fullName>CredHub Service Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Datanode</fullName>
    </customValue>
    <customValue>
        <fullName>DDL and Utility Statements</fullName>
    </customValue>
    <masterLabel>Component</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/classes/PortalNewCaseController_TC.cls
@isTest
private class PortalNewCaseController_TC {
   /* @isTest
    static void TC1(){
        TestDataUtil.dataValueMapCSData();
        User curUser=new User(Id = UserInfo.getUserID());
                 
        Account acc = new Account(Name='Test Account',Type='Prospect');
        insert acc;
        
        Contact con=new Contact(firstname='Test',lastname='Test',email='test@test.com',AccountID=acc.Id);
        insert con;        
        AccountContactRole__c AccountContactRole = new AccountContactRole__c(Account__c=acc.Id,AccountAccessLevel__c='Read', CaseAccessLevel__c='Test',Contact__c=con.Id,ContactAccessLevel__c='Test',Role__c='Test',User__c=curUser.Id);
        insert AccountContactRole;
        Id entitlementProcessId = [SELECT Id FROM SlaProcess WHERE SObjectType = 'Case' AND Name='Businesshourprocess'].Id;
        
        Entitlement ent = new Entitlement (AccountId=acc.Id, SLAProcessId = entitlementProcessId, Name = 'Test Entitlement');
        insert ent;
        String accid = [Select id, name from Account].Id;
        //String accid1 = [Select Accountid from User].AccountId;
        PortalNewCaseController.getEntitlementList();
        PortalNewCaseController.getRelatedContacts(accid);
        PortalNewCaseController.getRelatedEntitlements(accid);
        PortalNewCaseController.getAccountList();
    }
    @isTest
    static void TC2(){
        TestDataUtil.dataValueMapCSData();
        Account acc = new Account(Name='Test Account',Type='Prospect');
        insert acc;
        Contact con=new Contact(firstname='Test',lastname='Test',email='test@test.com',AccountID=acc.Id);
        insert con;
        
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Customer Community Manager' LIMIT 1];
        User usr = new User(LastName = 'Test1',FirstName='Test1',Alias = 'Test1',Email = 'Test1@acc.com',
                             Username = 'Test1@acc.com',ProfileId = profileId.id, TimeZoneSidKey = 'GMT', LanguageLocaleKey = 'en_US', 
                             EmailEncodingKey = 'UTF-8', LocaleSidKey = 'en_US',contactid=con.id);
        insert usr;
        
        System.runAs(usr){
            String accid=(String)acc.Id;
        PortalNewCaseController.getRelatedContacts(accid);
        }
        
    }
    @isTest
    static void TC3(){
        TestDataUtil.dataValueMapCSData();
        Account acc = new Account(Name='Test Account',Type='Prospect');
        insert acc;
        Account acc1 = new Account(Name='Test Account',Type='Prospect');
        insert acc1;   
        Contact con1=new Contact(firstname='Test',lastname='Test',email='test@test.com',AccountID=acc1.Id);
        insert con1;
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Customer Community Manager' LIMIT 1];
        User usr1 = new User(LastName = 'Test2',FirstName='Test2',Alias = 'Test2',Email = 'Test2@acc.com',
                             Username = 'Test2@acc.com',ProfileId = profileId.id, TimeZoneSidKey = 'GMT', LanguageLocaleKey = 'en_US', 
                             EmailEncodingKey = 'UTF-8', LocaleSidKey = 'en_US',contactid=con1.id);
        insert usr1;
        AccountContactRole__c AccountContactRole = new AccountContactRole__c(Account__c=acc.Id,AccountAccessLevel__c='Read', CaseAccessLevel__c='Test',Contact__c=con1.Id,ContactAccessLevel__c='Test',Role__c='Multiple PCN View All',User__c=usr1.Id);
        insert AccountContactRole;
        AccountShare AccShare = new AccountShare(AccountId = acc.Id, AccountAccessLevel = 'Edit', OpportunityAccessLevel = 'Read', CaseAccessLevel = 'Read', UserOrGroupId = usr1.Id);
        Insert AccShare;
       
        System.runAs(usr1){
        String accid1=(String)acc.Id;
        PortalNewCaseController.getEntitlementList();
        PortalNewCaseController.getRelatedContacts(accid1); 
        
        }
    }
    @isTest
    static void TC4(){
        TestDataUtil.dataValueMapCSData();
        Account acc = new Account(Name='Test Account',Type='Prospect');
        insert acc;
        Account acc1 = new Account(Name='Test Account',Type='Prospect');
        insert acc1;   
        Contact con1=new Contact(firstname='Test',lastname='Test',email='test@test.com',AccountID=acc1.Id);
        insert con1;
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Customer Community Manager' LIMIT 1];
        User usr1 = new User(LastName = 'Test2',FirstName='Test2',Alias = 'Test2',Email = 'Test2@acc.com',
                             Username = 'Test2@acc.com',ProfileId = profileId.id, TimeZoneSidKey = 'GMT', LanguageLocaleKey = 'en_US', 
                             EmailEncodingKey = 'UTF-8', LocaleSidKey = 'en_US',contactid=con1.id);
        insert usr1;
        AccountContactRole__c AccountContactRole = new AccountContactRole__c(Account__c=acc.Id,AccountAccessLevel__c='Read', CaseAccessLevel__c='Test',Contact__c=con1.Id,ContactAccessLevel__c='Test',Role__c='Test',User__c=usr1.Id);
        insert AccountContactRole;
        AccountShare AccShare = new AccountShare(AccountId = acc.Id, AccountAccessLevel = 'Edit', OpportunityAccessLevel = 'Read', CaseAccessLevel = 'Read', UserOrGroupId = usr1.Id);
        Insert AccShare;
       
        System.runAs(usr1){
        String accid1=(String)acc.Id;
        PortalNewCaseController.getEntitlementList();
        PortalNewCaseController.getRelatedContacts(accid1); 
        
        }
    }
    @isTest
    static void TC5()
    {
        TestDataUtil.dataValueMapCSData();
        Account acc = new Account(Name='Test Account',Type='Prospect',Special_Handling__c='EH - Executive Handling');
        insert acc;
        Contact con=new Contact(firstname='Test',lastname='Test',email='test@test.com',AccountID=acc.Id);
        insert con;
        ProductEntitlementMap__c PEM=new ProductEntitlementMap__c(Name='Test', Entitlement_Process__c='Test', Product_SKU__c='Test',SFDC_Product_Name__c='Test',Products__c='Test');
        insert PEM;
        Id entitlementProcessId12 = [SELECT Id FROM SlaProcess WHERE SObjectType = 'Case' AND Name='Businesshourprocess'].Id;
        
        Entitlement ent1 = new Entitlement (AccountId=acc.Id,ProductEntitlementMap__c=PEM.Id,StartDate= Date.newInstance(2016, 12, 9), EndDate=Date.newInstance(2025, 12, 9), SLAProcessId = entitlementProcessId12, Name = 'Test12 Entitlement');
        insert ent1;
        
        List<BusinessHours> bhs=[select id from BusinessHours];
        Id bhs1=(Id)bhs[0].ID;
        Case caseObj = new Case(ContactId = con.ID,AccountId = acc.Id,Status = 'Open',Origin = 'Email', EntitlementId=ent1.ID, BusinessHoursId=bhs1, Priority='Severity 1 - Critical',Subject='Test', Description='Test Description');
        insert caseObj;
        Case caseObj1 = new Case(ContactId = con.ID,AccountId = acc.Id,Status = 'Open',Origin = 'Email', BusinessHoursId=bhs1, Priority='Severity 1 - Critical',Subject='Test', Description='Test Description');
        insert caseObj1;
        List<String> liststr=new List<String> {'1','2','3'};
        PortalNewCaseController.createRecord(caseObj,liststr);
        PortalNewCaseController.createRecord(caseObj1,liststr);
        String str='Environment__c';
        CaseDep__c casde=new CaseDep__c(Name='Test CaseDep',Component__c='Test Component', Product__c='Test', ProductVersion__c='Test ProductVersion',  Subcomponent__c='Test Subcomponent');
        insert casde;
        
        PortalNewCaseController.getselectOptions(caseObj,str);
        PortalNewCaseController.getAllDepFieldValue(ent1.id);
        PortalNewCaseController.getSubCompValue('Test Component');
        PortalNewCaseController.getSendSafetyURL(acc.Id);
        PortalNewCaseController.getCurrentUser();
    }*/
    
   static testmethod void portalCaseCreation(){
        TestDataUtil.dataValueMapCSData();
        Account acc = TestDataUtil.createAccount();
        System.assert(acc.Id!=null);
        Contact pCont = TestDataUtil.createPortalContact();
        
        System.assert(pCont.Id!=null);
        TestDataUtil.createAccountContactRole(acc.Id,pCont.Id);
        Entitlement ent = TestDataUtil.createEntitlement(pCont.AccountId);
        System.assert(ent.Id != null);
        User usr = [Select Id ,AccountId,ProfileId from User where contactId =: pCont.Id];     
        System.assert(usr != null);
        System.assertEquals(pCont.AccountId,usr.AccountId);
        System.assert(usr.AccountId != acc.Id);
        DataValueMap__c csData = DataValueMap__c.getInstance('PortalManagerProfileId');
        csData.Data_Value__c = usr.ProfileId;
        update csData;
        System.assertEquals(usr.ProfileId,csData.Data_Value__c);
        AccountContactRole acr = new AccountContactRole(AccountId=acc.Id,ContactId=pCont.Id,Role='Multiple PCN View All');
        insert acr;
        System.assert(acr.Id != null);
        AccountShare AccShare = new AccountShare(AccountId = acc.Id, AccountAccessLevel = 'Read', OpportunityAccessLevel = 'Read', CaseAccessLevel = 'Read', UserOrGroupId = usr.Id);
        Insert AccShare;
        Case caseObj = new Case(Subject='Ignore Test Case' ,Case_Comments__c='Test Case Created', Description='Ignore Test Case' , AccountId=pCont.AccountId, ContactId =pCont.Id);
        
        System.runAs(usr){
            PortalNewCaseController.getEntitlementList();
            PortalNewCaseController.getRelatedContacts(acc.Id);
            PortalNewCaseController.getselectOptions(new Case(),'Environment__c');
            PortalNewCaseController.createRecord(caseObj,null);
        }
        Contact pCont1 = TestDataUtil.createPortalContact();
        AccountContactRole acr1 = new AccountContactRole(AccountId=pCont1.AccountId,ContactId=pCont1.Id,Role='Partner');
        insert acr1;
        AccountShare AccShare1 = new AccountShare(AccountId = pCont1.AccountId, AccountAccessLevel = 'Read', OpportunityAccessLevel = 'Read', CaseAccessLevel = 'Read', UserOrGroupId = usr.Id);
        Insert AccShare1;        
        System.runAs(usr){
            PortalNewCaseController.getRelatedContacts(pCont.AccountId);
            PortalNewCaseController.getRelatedContacts(pCont1.AccountId);
        }
        PortalNewCaseController.attachFileOnCase(caseObj.id,'');
        PortalNewCaseController.getSendSafetyURL(pCont.AccountId,caseObj.id);
        PortalNewCaseController.getSendSafetyURL(pCont.AccountId,null);
    }
    
    static testmethod void portalCaseCreation_1(){
        TestDataUtil.dataValueMapCSData();
        TestDataUtil.createCaseDep();
       
         List<Profile> lstProfile = TestDataUtil.getProfiles();
        List<DataValueMap__c>  csDataList =  new List<DataValueMap__c>();
        csDataList.add(new DataValueMap__c(Name='Pivotal - AccountShare Access',Data_Value__c='0PSf0000000DNtBGAW'));
        insert csDataList;
        
       
        Test.StartTest();
           Contact pCont = TestDataUtil.createPortalContact();
            System.assert(pCont.Id!=null);
            pCont.Interact_with_Community__c =true;
            pCont.Enable_Portal_User__c =true;
            pCont.View_Account_Cases__c =true;
            pCont.Customer_Admin__c=true;
            update pCont;
            System.debug('contact id-'+pCont.Id+'--'+pCont.Customer_Admin__c);
            User usr = [Select id,ContactId, AccountId,ProfileId from User where isActive=true and ContactId=:pCont.Id];
            system.debug('user pro'+usr.profileId);
            System.assert(usr!=Null,'User not created');
            Entitlement ent = TestDataUtil.createEntitlement(pCont.AccountId);
            Entitlement ent1 = TestDataUtil.createEntitlement(pCont.AccountId);
            System.assert(ent.Id != null);
          // User u= PortalNewCaseController.getCurrentUser();
         //  case caseObj = [select id from case limit 1];
           system.runAs(usr){
           user u= PortalNewCaseController.getCurrentUser();
            list<Account> accList = PortalNewCaseController.getAccountList();
            System.assert(!acclist.isEmpty());
           list<Entitlement> rEnt1 = PortalNewCaseController.getRelatedEntitlements(accList[0].Id);
           list<Entitlement> rEnt = new list<Entitlement>();
           rEnt.add(ent);
           rEnt.add(ent1);
           System.assert(!rEnt.isEmpty());

           /*Case caseObj = new Case(Subject='Ignore Test Case' , Description='Ignore Test Case' , AccountId=pCont.AccountId, ContactId =pCont.Id);
            caseObj.Priority = 'Severity 3 - Minor'; 
        caseObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Non-Technical').getRecordTypeId();
        insert caseObj;*/
           // System.assertEquals(caseObj.Id!=null,true,'Case Created');
            
          PortalNewCaseController.getAllDepFieldValue(rEnt[0].Id);
          portalNewCaseController.getSubCompValue(rEnt[0].Id,'Test Component');
         // portalNewCaseController.getSendSafetyURL(accList[0].Id,caseObj.Id);
          PortalNewCaseController.getRelatedContacts(accList[0].Id);
          
        //TestDataUtil.removeDataValueMapCSData();
        list<Entitlement> rEnt2 = PortalNewCaseController.getRelatedEntitlements(accList[0].Id);
          // PortalNewCaseController.createRecord(caseObj,null);
           }
        Test.StopTest();
}
}