src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region of the Account Owner</description>
        <formula>TEXT(Owner.Region__c)</formula>
        <inlineHelpText>Region of the Account Owner</inlineHelpText>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CNS_Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER West</fullName>
                </value>
                <value>
                    <fullName>AMER Fed</fullName>
                </value>
                <value>
                    <fullName>AMER ISR</fullName>
                </value>
                <value>
                    <fullName>AMER Labs</fullName>
                </value>
                <value>
                    <fullName>AMER PDE</fullName>
                </value>
                <value>
                    <fullName>AMER Data Sales</fullName>
                </value>
                <value>
                    <fullName>AMER Sub Renewals</fullName>
                </value>
                <value>
                    <fullName>AMER Other</fullName>
                </value>
                <value>
                    <fullName>APJ Australia New Zealand</fullName>
                </value>
                <value>
                    <fullName>APJ Greater China</fullName>
                </value>
                <value>
                    <fullName>APJ India</fullName>
                </value>
                <value>
                    <fullName>APJ ISR</fullName>
                </value>
                <value>
                    <fullName>APJ Japan</fullName>
                </value>
                <value>
                    <fullName>APJ Korea</fullName>
                </value>
                <value>
                    <fullName>APJ Other</fullName>
                </value>
                <value>
                    <fullName>APJ South Asia</fullName>
                </value>
                <value>
                    <fullName>APJ Southeast Asia</fullName>
                </value>
                <value>
                    <fullName>Bay Area</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Central North</fullName>
                </value>
                <value>
                    <fullName>Central West</fullName>
                </value>
                <value>
                    <fullName>EMEA Central</fullName>
                </value>
                <value>
                    <fullName>EMEA France &amp; S Europe</fullName>
                </value>
                <value>
                    <fullName>EMEA ISR</fullName>
                </value>
                <value>
                    <fullName>EMEA Labs</fullName>
                </value>
                <value>
                    <fullName>EMEA MEA</fullName>
                </value>
                <value>
                    <fullName>EMEA Other</fullName>
                </value>
                <value>
                    <fullName>EMEA UKI</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Labs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CNS Region</label>
    <nameField>
        <displayFormat>C-{00}</displayFormat>
        <label>CNS Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNS Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>This field is ready only, please contact the system administrator to change it.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Area__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AMER Central</fullName>
                </value>
                <value>
                    <fullName>AMER Data Sales</fullName>
                    <color>#9999FF</color>
                    <label>AMER Data Sales</label>
                </value>
                <value>
                    <fullName>AMER Dell Synergy</fullName>
                </value>
                <value>
                    <fullName>AMER East</fullName>
                </value>
                <value>
                    <fullName>AMER ISR</fullName>
                    <color>#66FFFF</color>
                    <label>AMER ISR</label>
                </value>
                <value>
                    <fullName>AMER Other</fullName>
                    <color>#DDDDDD</color>
                    <label>AMER Other</label>
                </value>
                <value>
                    <fullName>AMER PDE</fullName>
                    <color>#FF9966</color>
                    <label>AMER PDE</label>
                </value>
                <value>
                    <fullName>AMER South</fullName>
                </value>
                <value>
                    <fullName>AMER Sub Renewals</fullName>
                    <color>#FFFF66</color>
                    <label>AMER Sub Renewals</label>
                </value>
                <value>
                    <fullName>AMER-Support</fullName>
                </value>
                <value>
                    <fullName>AMER VMware Synergy</fullName>
                </value>
                <value>
                    <fullName>AMER West</fullName>
                    <color>#A53711</color>
                    <label>AMER West</label>
                </value>
                <value>
                    <fullName>APJ Australia New Zealand</fullName>
                    <color>#990000</color>
                    <label>APJ Australia New Zealand</label>
                </value>
                <value>
                    <fullName>APJ Greater China</fullName>
                    <color>#419249</color>
                    <label>APJ Greater China</label>
                </value>
                <value>
                    <fullName>APJ India</fullName>
                </value>
                <value>
                    <fullName>APJ ISR</fullName>
                    <color>#FF9900</color>
                    <label>APJ ISR</label>
                </value>
                <value>
                    <fullName>APJ Japan</fullName>
                    <color>#641CCF</color>
                    <label>APJ Japan</label>
                </value>
                <value>
                    <fullName>APJ Korea</fullName>
                    <color>#F96FB7</color>
                    <label>APJ Korea</label>
                </value>
                <value>
                    <fullName>APJ Other</fullName>
                    <color>#66E9BD</color>
                    <label>APJ Other</label>
                </value>
                <value>
                    <fullName>APJ South Asia</fullName>
                </value>
                <value>
                    <fullName>APJ Southeast Asia</fullName>
                    <color>#2F5D85</color>
                    <label>APJ Southeast Asia</label>
                </value>
                <value>
                    <fullName>APJ-Support</fullName>
                </value>
                <value>
                    <fullName>APJ VMWare Synergy</fullName>
                </value>
                <value>
                    <fullName>Bay Area</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                    <color>#0B24BE</color>
                    <label>Canada</label>
                </value>
                <value>
                    <fullName>Central North</fullName>
                    <color>#419249</color>
                    <label>Central North</label>
                </value>
                <value>
                    <fullName>Central West</fullName>
                </value>
                <value>
                    <fullName>Chatter Only</fullName>
                    <color>#663333</color>
                    <label>Chatter Only</label>
                </value>
                <value>
                    <fullName>EMEA - Central</fullName>
                </value>
                <value>
                    <fullName>EMEA Central FSI/Telco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OpportunityLineItemTriggerOppTeam_Test.cls
@isTest (SeeAllData=false)

private class OpportunityLineItemTriggerOppTeam_Test {


    static void SetupCustomSettingData(){
        TestDataUtil.dataValueMapCSData();
    }

    /* Test Methods */

    static testMethod void test_individual_team_member() {
    
 
        
        SetupCustomSettingData();
        PricebookEntry pbEntry = generatePricebook();

        Profile salesProfile = TestDataFactory.createProfile('Pivotal - Sales Rep');

        system.debug('==>salesProfile:' + salesProfile);
        
        User cnsRep = TestDataFactory.createUser(salesProfile.Id, true);
        //CNS_Region__c cnsRegion = TestDataFactory.createCNSRegion(cnsRep.Id, 'Pacific NorthWest');
        CNS_Region__c cnsRegion = TestDataFactory.createCNSRegion(cnsRep.Id, 'Pacific NorthWest');

        User oppOwner = TestDataFactory.createUser(salesProfile.Id, false);
        oppOwner.Region__c = 'Pacific NorthWest';
        insert oppOwner;

        //commented by Sun 10/08/2018 	
        Opportunity opp = generateOpportunityWithOwner(oppOwner);

        system.debug('==>oppOwner:' + oppOwner);
        
        Test.startTest();        

        System.runAs(oppOwner) {
            insert opp;

            OpportunityLineItem oppLineItem = TestDataFactory.createOpportunityLineItem(opp.Id, pbEntry.Id, 500.00, false);
            insert oppLineItem;
        }

        Test.stopTest();

        List<OpportunityLineItem> oppLineitems = [SELECT Id FROM OpportunityLineItem WHERE OpportunityId = :opp.Id];
        System.assertEquals(1, oppLineitems.size(), 'CNS Reps not on OpportunityLineItem');
    }

    static testMethod void test_cns_rep_opp_line_insert_ability() {
        SetupCustomSettingData();
        PricebookEntry pbEntry = generatePricebook();
        //commented by Sun 10/08/2018 
        //Opportunity opp = generateOpportunity();

        Profile salesProfile = TestDataFactory.createProfile('Pivotal - Sales Rep');

        User cnsRep = TestDataFactory.createUser(salesProfile.Id, true);
        CNS_Region__c cnsRegion = TestDataFactory.createCNSRegion(cnsRep.Id, 'Pacific NorthWest');

        User oppOwner = TestDataFactory.createUser(salesProfile.Id, false);
        oppOwner.Region__c = 'Pacific NorthWest';
        insert oppOwner;
        
        //added by Sun 10/08/2018 
        Opportunity opp = generateOpportunityWithOwner(oppOwner);

        System.runAs(oppOwner) {
            insert opp;

            OpportunityLineItem oppLineItem = TestDataFactory.createOpportunityLineItem(opp.Id, pbEntry.Id, 500.00, false);
            insert oppLineItem;
        }

        Test.startTest();

        try {
            System.runAs(cnsRep) {
                OpportunityLineItem oppLineItem = TestDataFactory.createOpportunityLineItem(opp.Id, pbEntry.Id, 500.00, false);
                insert oppLineItem;
            }
        } catch (Exception ex) {
            System.assert(false, 'CNS Rep unable to insert opp line');
        }

        Test.stopTest();
    }

    static testMethod void test_multiple_team_members() {
        
        SetupCustomSettingData();
        PricebookEntry pbEntry = generatePricebook();
        //commented by Sun 10/08/2018 
        //Opportunity opp = generateOpportunity();

        Profile salesProfile = TestDataFactory.createProfile('Pivotal - Sales Rep');
        User cnsRep1 = TestDataFactory.createUser(salesProfile.Id, true);
        CNS_Region__c cnsRegion1 = TestDataFactory.createCNSRegion(cnsRep1.Id, 'Pacific NorthWest');

        User cnsRep2 = TestDataFactory.createUser(salesProfile.Id, true);
        CNS_Region__c cnsRegion2 = TestDataFactory.createCNSRegion(cnsRep2.Id, 'Pacific NorthWest');

        User oppOwner = TestDataFactory.createUser(salesProfile.Id, false);
        oppOwner.Region__c = 'Pacific NorthWest';
        insert oppOwner;
        
        //added by Sun 10/08/2018 
        Opportunity opp = generateOpportunityWithOwner(oppOwner);

        Test.startTest();

        System.runAs(oppOwner) {
            insert opp;

            OpportunityLineItem oppLineItem = TestDataFactory.createOpportunityLineItem(opp.Id, pbEntry.Id, 500.00, false);
            insert oppLineItem;
        }

        Test.stopTest();

        List<OpportunityLineItem> oppLineitems = [SELECT Id FROM OpportunityLineItem WHERE OpportunityId = :opp.Id];
        System.assertEquals(1, oppLineitems.size(), 'CNS Reps not on OpportunityLineItem');
    }

    static testMethod void test_multiple_opportunities() {
        SetupCustomSettingData();
        PricebookEntry pbEntry = generatePricebook();
        
        //commented by Sun 10/08/2018 
        //Opportunity northwestOpp = generateOpportunity();
        //Opportunity southwestOpp = generateOpportunity();

        Profile salesProfile = TestDataFactory.createProfile('Pivotal - Sales Rep');
        User cnsRepNorth = TestDataFactory.createUser(salesProfile.Id, true);
        CNS_Region__c cnsRegion1 = TestDataFactory.createCNSRegion(cnsRepNorth.Id, 'Pacific NorthWest');

        User cnsRepSouth = TestDataFactory.createUser(salesProfile.Id, true);
        CNS_Region__c cnsRegion2 = TestDataFactory.createCNSRegion(cnsRepSouth.Id, 'Pacific SouthWest');

        User oppOwnerNorth = TestDataFactory.createUser(salesProfile.Id, false);
        oppOwnerNorth.Region__c = 'Pacific NorthWest';
        insert oppOwnerNorth;

        User oppOwnerSouth = TestDataFactory.createUser(salesProfile.Id, false);
        oppOwnerSouth.Region__c = 'Pacific SouthWest';
        insert oppOwnerSouth;

        //added by Sun 10/08/2018 
        Opportunity northwestOpp = generateOpportunityWithOwner(oppOwnerNorth);
        Opportunity southwestOpp = generateOpportunityWithOwner(oppOwnerSouth);
        
        Test.startTest();

        System.runAs(oppOwnerNorth) {
            insert northwestOpp;
        }

        System.runAs(oppOwnerSouth) {
            insert southwestOpp;
        }

        List<OpportunityLineItem> oppLineList = new List<OpportunityLineItem>();
        oppLineList.add(TestDataFactory.createOpportunityLineItem(northwestOpp.Id, pbEntry.Id, 500.00, false));
        oppLineList.add(TestDataFactory.createOpportunityLineItem(southwestOpp.Id, pbEntry.Id, 500.00, false));

        insert oppLineList;

        Test.stopTest();

        List<OpportunityLineItem> oppLineitems = [SELECT Id FROM OpportunityLineItem WHERE PricebookEntryId = :pbEntry.Id];
        System.assertEquals(2, oppLineitems.size(), 'CNS Reps not on OpportunityLineItem');
    }

    static testMethod void test_no_cns_rep_for_region() {
        SetupCustomSettingData();
        PricebookEntry pbEntry = generatePricebook();
        //commented by Sun 10/08/2018 
        //Opportunity opp = generateOpportunity();

        Profile salesProfile = TestDataFactory.createProfile('Pivotal - Sales Rep');
        User oppOwner = TestDataFactory.createUser(salesProfile.Id, false);
        oppOwner.Region__c = 'Pacific NorthWest';
        insert oppOwner;
        
        //added by Sun 10/08/2018 
        Opportunity opp = generateOpportunityWithOwner(oppOwner);

        Test.startTest();

        System.runAs(oppOwner) {
            insert opp;

            OpportunityLineItem oppLineItem = TestDataFactory.createOpportunityLineItem(opp.Id, pbEntry.Id, 500.00, false);
            insert oppLineItem;
        }

        Test.stopTest();

        List<OpportunityLineItem> oppLineitems = [SELECT Id FROM OpportunityLineItem WHERE OpportunityId = :opp.Id];
        System.assertEquals(1, oppLineitems.size(), 'CNS Reps not on OpportunityLineItem');
    }

    static testMethod void test_multiple_line_inserts() {
        SetupCustomSettingData();
        PricebookEntry pbEntry = generatePricebook();
        //commented by Sun 10/08/2018 
        //Opportunity opp = generateOpportunity();

        Profile salesProfile = TestDataFactory.createProfile('Pivotal - Sales Rep');
        User cnsRep = TestDataFactory.createUser(salesProfile.Id, true);
        CNS_Region__c cnsRegion = TestDataFactory.createCNSRegion(cnsRep.Id, 'Pacific NorthWest');

        User oppOwner = TestDataFactory.createUser(salesProfile.Id, false);
        oppOwner.Region__c = 'Pacific NorthWest';
        insert oppOwner;
        
        //added by Sun 10/08/2018 
        Opportunity opp = generateOpportunityWithOwner(oppOwner);

        Test.startTest();

        System.runAs(oppOwner) {
            insert opp;

            List<OpportunityLineItem> oppLineList = new List<OpportunityLineItem>();
            oppLineList.add(TestDataFactory.createOpportunityLineItem(opp.Id, pbEntry.Id, 500.00, false));
            oppLineList.add(TestDataFactory.createOpportunityLineItem(opp.Id, pbEntry.Id, 500.00, false));

            insert oppLineList;
        }

        Test.stopTest();

        List<OpportunityLineItem> oppLineitems = [SELECT Id FROM OpportunityLineItem WHERE OpportunityId = :opp.Id];
        System.assertEquals(2, oppLineitems.size(), 'CNS Reps not on OpportunityLineItem');
    }

    /* Private Methods */

    private static PricebookEntry generatePricebook() {
        Product2 product = TestDataFactory.createProduct2(true);
        return TestDataFactory.createPricebookEntry(product.Id, 5000.00, true);
    }

    private static Opportunity generateOpportunity() {
        Account acc = TestDataFactory.createAccount(true);
        
        return TestDataFactory.createOpportunity(acc.Id, false);
    }

    private static Opportunity generateOpportunityWithOwner(User owner) {
        Account acc = TestDataFactory.createAccount(true);
        acc.ownerId = owner.id;
        update acc;
        
        return TestDataFactory.createOpportunity(acc.Id, false);
    }

}