src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Problem::Account / Dashboard</fullName>
                </value>
                <value>
                    <fullName>Problem::Defect</fullName>
                </value>
                <value>
                    <fullName>Problem::Documentation</fullName>
                </value>
                <value>
                    <fullName>Problem::Error</fullName>
                </value>
                <value>
                    <fullName>Problem::Implementation</fullName>
                </value>
                <value>
                    <fullName>Problem::Installation</fullName>
                </value>
                <value>
                    <fullName>Problem::Logging</fullName>
                </value>
                <value>
                    <fullName>Problem::Performance</fullName>
                </value>
                <value>
                    <fullName>Problem::Security</fullName>
                </value>
                <value>
                    <fullName>Problem::Technical Issues</fullName>
                </value>
                <value>
                    <fullName>Problem::Upgrade</fullName>
                </value>
                <value>
                    <fullName>Question::Contract / Maintenance / Licensing</fullName>
                </value>
                <value>
                    <fullName>Question::Partnership / Business Development</fullName>
                </value>
                <value>
                    <fullName>Question::Software Availability / Compatibility / Upgrades</fullName>
                </value>
                <value>
                    <fullName>Request::Customer Service Improvement</fullName>
                </value>
                <value>
                    <fullName>Request::Documentation Improvement</fullName>
                </value>
                <value>
                    <fullName>Request::Product Feature Improvement</fullName>
                </value>
                <value>
                    <fullName>Remote Access Meetings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_KB_Article__c</fullName>
        <label>Related KB Article</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KB needed</fullName>
                    <label>KB Needed</label>
                </value>
                <value>
                    <fullName>KB/Doc exists</fullName>
                    <label>KB/Doc Exists</label>
                </value>
                <value>
                    <fullName>KB Not Applicable</fullName>
                    <isActive>false</isActive>
                    <label>KB Not Applicable</label>
                </value>
                <value>
                    <fullName>To be Filled Later</fullName>
                    <isActive>false</isActive>
                    <label>To be Filled Later</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ISV</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>3rd Party Software</fullName>
                </value>
                <value>
                    <fullName>Configuration</fullName>
                </value>
                <value>
                    <fullName>Customer Education</fullName>
                </value>
                <value>
                    <fullName>Defect Reported</fullName>
                </value>
                <value>
                    <fullName>Documentation</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Environment/Hardware</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information/Unresolved</fullName>
                </value>
                <value>
                    <fullName>Known Issue</fullName>
                </value>
                <value>
                    <fullName>Known Limitation</fullName>
                </value>
                <value>
                    <fullName>Not Entitled</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Product Fix</fullName>
                </value>
                <value>
                    <fullName>To Be Filled Later</fullName>
                </value>
                <value>
                    <fullName>Won't Fix</fullName>
                </value>
                <value>
                    <fullName>Workaround</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Opportunity_Root_Cause__c</fullName>
        <label>Prevention Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Management - Version Mgt</fullName>
                    <label>Account Management</label>
                </value>
                <value>
                    <fullName>Customer Education</fullName>
                </value>
                <value>
                    <fullName>Product Improvement - Known</fullName>
                    <label>Product Improvement - Already Reported</label>
                </value>
                <value>
                    <fullName>Product Improvement - New</fullName>
                </value>
                <value>
                    <fullName>Self Resolve - Community Forum Update</fullName>
                    <label>Self Resolve - Community Forum Post</label>
                </value>
                <value>
                    <fullName>Self Resolve - Knowledgebase</fullName>
                    <label>Self Resolve - Create Knowledge Article</label>
                </value>
                <value>
                    <fullName>Self Resolve - Documentation Update</fullName>
                    <label>Self Resolve - Documentation Improvement</label>
                </value>
                <value>
                    <fullName>Field Engagement</fullName>
                    <isActive>false</isActive>
                    <label>Field Engagement</label>
                </value>
                <value>
                    <fullName>Improved Logging</fullName>
                    <isActive>false</isActive>
                    <label>Improved Logging</label>
                </value>
                <value>
                    <fullName>Improved Monitoring</fullName>
                    <isActive>false</isActive>
                    <label>Improved Monitoring</label>
                </value>
                <value>
                    <fullName>Insufficient Information / Not reproduceable</fullName>
                    <isActive>false</isActive>
                    <label>Insufficient Information / Not reproduceable</label>
                </value>
                <value>
                    <fullName>New Feature</fullName>
                    <isActive>false</isActive>
                    <label>New Feature</label>
                </value>
                <value>
                    <fullName>Product Defect</fullName>
                    <isActive>false</isActive>
                    <label>Product Defect</label>
                </value>
                <value>
                    <fullName>Regular Maintenance</fullName>
                    <isActive>false</isActive>
                    <label>Regular Maintenance</label>
                </value>
                <value>
                    <fullName>Upsell Opportunity - Field Services</fullName>
                    <isActive>false</isActive>
                    <label>Upsell Opportunity - Field Services</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Steps_to_Resolve__c</fullName>
        <label>Steps to Resolve</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party/ISV Software Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Application Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Environment Issue</fullName>
                </value>
                <value>
                    <fullName>Documented Limitation</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>Duplicate Issue (Tracked in Different Ticket)</fullName>
                </value>
                <value>
                    <fullName>Engineering Intervention Required</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Fix in Higher Version(Upgrade)</fullName>
                    <label>Fix in Higher Version (Upgrade)</label>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
                <value>
                    <fullName>Reconfig Network Configuration</fullName>
                    <label>Network Configuration</label>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Product Configuration</fullName>
                </value>
                <value>
                    <fullName>Reported Product Defect (pending fix)</fullName>
                </value>
                <value>
                    <fullName>VM/JVM Configuration</fullName>
                </value>
                <value>
                    <fullName>Workaround Provided</fullName>
                </value>
                <value>
                    <fullName>Works as Designed</fullName>
                </value>
                <value>
                    <fullName>Escalation Acknowledged</fullName>
                    <isActive>false</isActive>
                    <label>Escalation Acknowledged</label>
                </value>
                <value>
                    <fullName>Hardware Repair/Replacement</fullName>
                    <isActive>false</isActive>
                    <label>Hardware Repair/Replacement</label>
                </value>
                <value>
                    <fullName>Install hot fix</fullName>
                    <isActive>false</isActive>
                    <label>Install hot fix</label>
                </value>
                <value>
                    <fullName>Known Issue - No fix available yet</fullName>
                    <isActive>false</isActive>
                    <label>Known Issue - No fix available yet</label>
                </value>
                <value>
                    <fullName>Notification Acknowedged</fullName>
                    <isActive>false</isActive>
                    <label>Notification Acknowedged</label>
                </value>
                <value>
                    <fullName>Provide instructions</fullName>
                    <isActive>false</isActive>
                    <label>Provide instructions</label>
                </value>
                <value>
                    <fullName>Reconfig Pivotal software</fullName>
                    <isActive>false</isActive>
                    <label>Reconfig Pivotal software</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Technical</fullName>
        <active>true</active>
        <businessProcess>Pivotal Support</businessProcess>
        <label>Technical</label>
    </recordTypes>
</CustomObject>

src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>Support_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be true when user have support exception</description>
        <label>Support Exception</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/classes/PS_EntitlementTriggerHandler_TC.cls
/*******************************************************************************************************************
* Apex Class Name  : PS_EntitlementTriggerHandler_TC
* Version          : 1.0
* Created Date     : 28 Oct 2017
* Function         : Class is used test  PS_EntitlementTriggerHandler - Entitlement create /update
* Modification Log : 
*
* Developer                        Date                       Description
* ------------------------------------------------------------------------------------------------------------------
* Deepa Lakamanhalli            28/10/2017            Test Class to test  PS_EntitlementTriggerHandler
* ------------------------------------------------------------------------------------------------------------------
********************************************************************************************************************
*/
@isTest
Private Class PS_EntitlementTriggerHandler_TC{
    private testmethod static void casecountTestMethod(){
        TestDataUtil.dataValueMapCSData(); 
        Contact con = TestDataUtil.createContact();
        System.assert(con.Id != null);
        Entitlement ent1 = TestDataUtil.createEntitlement(con.AccountId);
        ent1.Support_Exception__c = true;
        update ent1;
        
        case cObj = TestDataUtil.createTechnicalCase();
        System.assert(cObj.EntitlementId!=null);
        case cObj1 = TestDataUtil.createTechnicalCase();
        cObj1.AccountId = cObj.AccountId;
        cObj1.EntitlementId = cObj.EntitlementId;        
        cObj1.Resolution_Code__c ='Not Entitled';
        Test.startTest();
        update cObj1;
        cObj1.Case_Type__c ='Escalation';
        cObj1.Related_KB_Article__c = 'KB needed';
        cObj1.Resolution__c = 'resolution';
        cObj1.Resolution_Opportunity_Root_Cause__c = 'Customer Education';
        cObj1.Steps_to_Resolve__c = 'Downgrade';
        cObj1.Status ='Solved';
        update cObj1;
        Test.stopTest();
       
        entitlement ent = new entitlement();
        ent.Id = cObj.EntitlementId;
        ent.Support_Exception__c = true;
        ent.AccountId = cObj.AccountId;     
        update ent;
        
        ent.Support_Exception__c = false;
        update ent;
  
    }
    
    private testmethod static void casecountGranted(){
        TestDataUtil.dataValueMapCSData(); 
        Contact con = TestDataUtil.createContact();
        System.assert(con.Id != null);
        Entitlement ent1 = TestDataUtil.createEntitlement(con.AccountId);
        ent1.Support_Exception__c = true;
        update ent1;
        
        case cObj = TestDataUtil.createTechnicalCase();
        System.assert(cObj.EntitlementId!=null);
        case cObj1 = TestDataUtil.createTechnicalCase();
        cObj1.AccountId = cObj.AccountId;
        cObj1.EntitlementId = cObj.EntitlementId;        
        cObj1.Resolution_Code__c ='ISV';
        Test.startTest(); 
        update cObj1;
        cObj1.Case_Type__c ='Escalation';
        cObj1.Related_KB_Article__c = 'KB needed';
        cObj1.Resolution__c = 'resolution';
        cObj1.Resolution_Opportunity_Root_Cause__c = 'Customer Education';
        cObj1.Steps_to_Resolve__c = 'Downgrade';
        cObj1.Status ='Solved';
        update cObj1;
        Test.stopTest(); 
       
        entitlement ent = new entitlement();
        ent.Id = cObj.EntitlementId;
        ent.Support_Exception__c = true;
        ent.AccountId = cObj.AccountId;     
        update ent;
        
        ent.Support_Exception__c = false;
        update ent;
  
    }
    
        static testMethod  void  countUpdate(){
        TestDataUtil.dataValueMapCSData(); 
        Contact conRecord = TestDataUtil.createContact(); 
        System.assert(conRecord.Id != null);      
        Account accRecord = TestDataUtil.createAccount();
        Entitlement ent1 = TestDataUtil.createEntitlement(accRecord.Id);
        ent1.Support_Exception__c = true;
        update ent1;
        
        case cObj = new case();
        cObj.Subject = 'Ignore Test Case';
        cObj.Description ='Ignore Test Case creation via Test Class';
        cObj.ContactId = conRecord.Id;
        cObj.AccountId = accRecord.Id;
        cObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj.EntitlementId = ent1.Id;
        cObj.Products__c='Alpine Chorus for Pivotal Data Suite';
        cObj.Priority='Severity 1 - Critical'; 
        cObj.Resolution_Code__c='ISV';
        cObj.Case_Type__c ='Escalation';
        cObj.Related_KB_Article__c = 'KB needed';
        cObj.Resolution__c = 'resolution';
        cObj.Resolution_Opportunity_Root_Cause__c = 'Customer Education';
        cObj.Steps_to_Resolve__c = 'Downgrade';
        cObj.Status='Solved';
        insert cObj;
        System.assert(cObj.Id !=null , 'Failed to create Technical Case'); 
        
               
            }
       
    
}