src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Problem::Account / Dashboard</fullName>
                </value>
                <value>
                    <fullName>Problem::Defect</fullName>
                </value>
                <value>
                    <fullName>Problem::Documentation</fullName>
                </value>
                <value>
                    <fullName>Problem::Error</fullName>
                </value>
                <value>
                    <fullName>Problem::Implementation</fullName>
                </value>
                <value>
                    <fullName>Problem::Installation</fullName>
                </value>
                <value>
                    <fullName>Problem::Logging</fullName>
                </value>
                <value>
                    <fullName>Problem::Performance</fullName>
                </value>
                <value>
                    <fullName>Problem::Security</fullName>
                </value>
                <value>
                    <fullName>Problem::Technical Issues</fullName>
                </value>
                <value>
                    <fullName>Problem::Upgrade</fullName>
                </value>
                <value>
                    <fullName>Question::Contract / Maintenance / Licensing</fullName>
                </value>
                <value>
                    <fullName>Question::Partnership / Business Development</fullName>
                </value>
                <value>
                    <fullName>Question::Software Availability / Compatibility / Upgrades</fullName>
                </value>
                <value>
                    <fullName>Request::Customer Service Improvement</fullName>
                </value>
                <value>
                    <fullName>Request::Documentation Improvement</fullName>
                </value>
                <value>
                    <fullName>Request::Product Feature Improvement</fullName>
                </value>
                <value>
                    <fullName>Remote Access Meetings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InboundEmailAlias__c</fullName>
        <label>InboundEmailAlias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_KB_Article__c</fullName>
        <label>Related KB Article</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KB needed</fullName>
                    <label>KB Needed</label>
                </value>
                <value>
                    <fullName>KB/Doc exists</fullName>
                    <label>KB/Doc Exists</label>
                </value>
                <value>
                    <fullName>KB Not Applicable</fullName>
                    <isActive>false</isActive>
                    <label>KB Not Applicable</label>
                </value>
                <value>
                    <fullName>To be Filled Later</fullName>
                    <isActive>false</isActive>
                    <label>To be Filled Later</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ISV</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>3rd Party Software</fullName>
                </value>
                <value>
                    <fullName>Configuration</fullName>
                </value>
                <value>
                    <fullName>Customer Education</fullName>
                </value>
                <value>
                    <fullName>Defect Reported</fullName>
                </value>
                <value>
                    <fullName>Documentation</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Environment/Hardware</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information/Unresolved</fullName>
                </value>
                <value>
                    <fullName>Known Issue</fullName>
                </value>
                <value>
                    <fullName>Known Limitation</fullName>
                </value>
                <value>
                    <fullName>Not Entitled</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Product Fix</fullName>
                </value>
                <value>
                    <fullName>To Be Filled Later</fullName>
                </value>
                <value>
                    <fullName>Won't Fix</fullName>
                </value>
                <value>
                    <fullName>Workaround</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Special_Handling_Instructions__c</fullName>
        <description>This field will display will display Handling Instructions on case</description>
        <label>Handling Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Steps_to_Resolve__c</fullName>
        <label>Steps to Resolve</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party/ISV Software Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Application Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Environment Issue</fullName>
                </value>
                <value>
                    <fullName>Documented Limitation</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>Duplicate Issue (Tracked in Different Ticket)</fullName>
                </value>
                <value>
                    <fullName>Engineering Intervention Required</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Fix in Higher Version(Upgrade)</fullName>
                    <label>Fix in Higher Version (Upgrade)</label>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
                <value>
                    <fullName>Reconfig Network Configuration</fullName>
                    <label>Network Configuration</label>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Product Configuration</fullName>
                </value>
                <value>
                    <fullName>Reported Product Defect (pending fix)</fullName>
                </value>
                <value>
                    <fullName>VM/JVM Configuration</fullName>
                </value>
                <value>
                    <fullName>Workaround Provided</fullName>
                </value>
                <value>
                    <fullName>Works as Designed</fullName>
                </value>
                <value>
                    <fullName>Escalation Acknowledged</fullName>
                    <isActive>false</isActive>
                    <label>Escalation Acknowledged</label>
                </value>
                <value>
                    <fullName>Hardware Repair/Replacement</fullName>
                    <isActive>false</isActive>
                    <label>Hardware Repair/Replacement</label>
                </value>
                <value>
                    <fullName>Install hot fix</fullName>
                    <isActive>false</isActive>
                    <label>Install hot fix</label>
                </value>
                <value>
                    <fullName>Known Issue - No fix available yet</fullName>
                    <isActive>false</isActive>
                    <label>Known Issue - No fix available yet</label>
                </value>
                <value>
                    <fullName>Notification Acknowedged</fullName>
                    <isActive>false</isActive>
                    <label>Notification Acknowedged</label>
                </value>
                <value>
                    <fullName>Provide instructions</fullName>
                    <isActive>false</isActive>
                    <label>Provide instructions</label>
                </value>
                <value>
                    <fullName>Reconfig Pivotal software</fullName>
                    <isActive>false</isActive>
                    <label>Reconfig Pivotal software</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting For R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Waiting For Support</fullName>
                </value>
                <value>
                    <fullName>Waiting For Customer</fullName>
                </value>
                <value>
                    <fullName>RPS Hold</fullName>
                </value>
                <value>
                    <fullName>Waiting for RPS</fullName>
                    <isActive>false</isActive>
                    <label>Waiting for RPS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Versions__c</fullName>
        <label>Product Version</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Products__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Version</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Technical</fullName>
        <active>true</active>
        <businessProcess>Pivotal Support</businessProcess>
        <label>Technical</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Handling_Instructions__c.object
<CustomObject>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <description>This object is used to display Special Handling Instructions</description>
    <label>Handling Instructions</label>
    <nameField>
        <label>Special Handling Instructions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Handling Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Version.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0.1</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.3</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.4</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.8</fullName>
    </customValue>
    <customValue>
        <fullName>1.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.3</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.4</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.5</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.6</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.X</fullName>
    </customValue>
    <customValue>
        <fullName>1.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.5</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.9</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.10</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.14</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.15</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2.2</fullName>
    </customValue>
    <customValue>
        <fullName>2.4</fullName>
    </customValue>
    <masterLabel>Version</masterLabel>
</GlobalValueSet>

src/classes/PS_CaseTriggerHandler_Test.cls
@isTest
Private class PS_CaseTriggerHandler_Test {
    static testMethod  void  technicalCase(){
        TestDataUtil.dataValueMapCSData(); 
        Case cObj = TestDataUtil.createTechnicalCase();
        System.assert(cObj.Id !=null , 'Failed to create Technical Case');  
        cObj.InboundEmailAlias__c='ehsp.scqa@pivotal.io';
        cObj.Status='On Hold';
        // cObj.Sub_Status__c = 'RPS Hold';
        update cObj;
        cObj.Status='Open';
        update cObj;
        
        
    }

    static testMethod  void  technicalCaseChangeAccount(){
        TestDataUtil.dataValueMapCSData(); 
        Contact con = TestDataUtil.createContact();
        System.assert(con.Id != null);
        Entitlement ent = TestDataUtil.createEntitlement(con.AccountId);
        Special_Handling_Instructions__c shi = TestDataUtil.createSpecialHandling(con.AccountId);
        case cObj = new case();
        cObj.Subject = 'Ignore Test Case';
        cObj.Description ='Ignore Test Case creation via Test Class';
        cObj.ContactId = (con !=null ? con.Id :null);
        cObj.AccountId = (con.AccountId!=null ? con.AccountId :null);
        cObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj.EntitlementId = ent.Id;
        cObj.Products__c='Pivotal Greenplum';
        //cObj.Versions__c='2.4';
        cObj.Priority='Severity 1 - Critical'; 
        cObj.Status='Solved';
        insert cObj;
        //Special_Handling_Instructions__c shi = TestDataUtil.createSpecialHandling(cObj.AccountId);
        System.assert(cObj.Id !=null , 'Failed to create Technical Case'); 
        Account accRecord = TestDataUtil.createAccount();
        Entitlement ent1 = TestDataUtil.createEntitlement(accRecord.Id);
        cObj.EntitlementId = ent1.Id;
        cObj.AccountId = accRecord.Id;
        update cObj;
        
        case cObj1 = new case();
        cObj1.Subject = 'Ignore Test Case';
        cObj1.Description ='Ignore Test Case creation via Test Class';
        cObj1.ContactId = (con !=null ? con.Id :null);
        cObj1.AccountId = (con.AccountId!=null ? con.AccountId :null);
        cObj1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj1.EntitlementId = ent.Id;
        cObj1.Products__c='Pivotal Greenplum';
        //cObj.Versions__c='2.4';
        cObj1.Priority='Severity 1 - Critical'; 
        cObj1.Resolution_Code__c='Not Entitled';
        cObj1.Related_KB_Article__c='KB Not Applicable';
        cObj1.Case_Type__c='Escalation';
        cObj1.Resolution__c='Test';
        cObj1.Steps_to_Resolve__c='Downgrade';
        cObj1.Resolution_Opportunity_Root_Cause__c='Customer Education';
        cObj1.Status ='Open';
        insert cObj1;
        //Special_Handling_Instructions__c shi = TestDataUtil.createSpecialHandling(cObj.AccountId);
        System.assert(cObj1.Id !=null , 'Failed to create Technical Case'); 
        cObj1.Status ='Solved';
        update cObj1;
        Account accRecord1 = TestDataUtil.createAccount();
        Entitlement ent2 = TestDataUtil.createEntitlement(accRecord1.Id);
        cObj1.EntitlementId = ent2.Id;
        cObj1.AccountId = accRecord1.Id;
        update cObj1;
    }
    
    static testMethod  void  technicalCase2(){
        TestDataUtil.dataValueMapCSData(); 
        Contact con = TestDataUtil.createContact();
        System.assert(con.Id != null);
        Entitlement ent = TestDataUtil.createEntitlement(con.AccountId);
        ent.Support_Exception__c = true;
        update ent;
        Special_Handling_Instructions__c shi = TestDataUtil.createSpecialHandling(con.AccountId);
        case cObj = new case();
        cObj.Subject = 'Ignore Test Case';
        cObj.Description ='Ignore Test Case creation via Test Class';
        cObj.ContactId = (con !=null ? con.Id :null);
        cObj.AccountId = (con.AccountId!=null ? con.AccountId :null);
        cObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj.EntitlementId = ent.Id;
        cObj.Products__c='Pivotal Greenplum';
        //cObj.Versions__c='2.4';
        cObj.Priority='Severity 1 - Critical'; 
        insert cObj;
        //Special_Handling_Instructions__c shi = TestDataUtil.createSpecialHandling(cObj.AccountId);
        System.assert(cObj.Id !=null , 'Failed to create Technical Case');  
        cObj.InboundEmailAlias__c='ehsp.scqa@pivotal.io';
        cObj.Status='On Hold';
        // cObj.Sub_Status__c = 'RPS Hold';
        update cObj;
        cObj.Status='Open';
        update cObj;
        test.starttest();
        case cObj1 = new case();
        cObj1.Subject = 'Ignore Test Case1';
        cObj1.Description ='Ignore Test Case creation via Test Class1';
        cObj1.ContactId = (con !=null ? con.Id :null);
        cObj1.AccountId = (con.AccountId!=null ? con.AccountId :null);
        cObj1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj1.EntitlementId = ent.Id;
        cObj1.Products__c='Pivotal Greenplum';
        //cObj.Versions__c='2.4';
        cObj1.Priority='Severity 1 - Critical'; 
        insert cObj1;
        System.assert(cObj1.Id !=null , 'Failed to create Technical Case1');
        //Removing as this is always failing even though products__c match in both this class and testdatautils
        //System.assert(cObj1.Products__c !=shi.Products__c  , 'Products match not found');
        test.stoptest();
     }
        
        static testMethod  void  technicalCase3(){
        TestDataUtil.dataValueMapCSData(); 
        Contact con = TestDataUtil.createContact();
        System.assert(con.Id != null);
        Entitlement ent = TestDataUtil.createEntitlement(con.AccountId);
        ent.Support_Exception__c = true;
        update ent;
        Special_Handling_Instructions__c shi = TestDataUtil.createSpecialHandling(con.AccountId);
        test.starttest();
        case cObj2 = new case();
        cObj2.Subject = 'Ignore Test Case2';
        cObj2.Description ='Ignore Test Case creation via Test Class2';
        cObj2.ContactId = (con !=null ? con.Id :null);
        cObj2.AccountId = (con.AccountId!=null ? con.AccountId :null);
        cObj2.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj2.EntitlementId = ent.Id;
        cObj2.Products__c='Pivotal Greenplum';
        //cObj.Versions__c='2.4';
        cObj2.Priority='Severity 1 - Critical'; 
        cObj2.Resolution_Code__c='Not Entitled';
        cObj2.Related_KB_Article__c='KB Not Applicable';
        cObj2.Case_Type__c='Escalation';
        cObj2.Resolution__c='Test';
        cObj2.Steps_to_Resolve__c='Downgrade';
        cObj2.Resolution_Opportunity_Root_Cause__c='Customer Education';
        cObj2.Status ='Solved';
        insert cObj2;
        System.assert(cObj2.Id !=null , 'Failed to create Technical Case2');
         
         case cObj3 = new case();
        cObj3.Subject = 'Ignore Test Case3';
        cObj3.Description ='Ignore Test Case creation via Test Class3';
        cObj3.ContactId = (con !=null ? con.Id :null);
        cObj3.AccountId = (con.AccountId!=null ? con.AccountId :null);
        cObj3.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj3.EntitlementId = ent.Id;
        cObj3.Products__c='Pivotal Greenplum';
        //cObj.Versions__c='2.4';
        cObj3.Priority='Severity 1 - Critical'; 
        cObj3.Resolution_Code__c ='Configuration';
        cObj3.Status ='Solved';
        insert cObj3 ;
        System.assert(cObj3.Id !=null , 'Failed to create Technical Case3');
        
        
        case cObj4 = new case();
        cObj4.Subject = 'Ignore Test Case4';
        cObj4.Description ='Ignore Test Case creation via Test Class4';
        cObj4.ContactId = (con !=null ? con.Id :null);
        cObj4.AccountId = (con.AccountId!=null ? con.AccountId :null);
        cObj4.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj4.EntitlementId = ent.Id;
        cObj4.Products__c='Pivotal Greenplum';
        //cObj.Versions__c='2.4';
        cObj4.Priority='Severity 1 - Critical'; 
        cObj4.Resolution_Code__c ='Configuration';
        cObj4.Status ='Solved';
        insert cObj4 ;
        System.assert(cObj4.Id !=null , 'Failed to create Technical Case4');
        delete cObj4 ;
        test.stoptest();
        
        
        
    }
    
            static testMethod void nonTechnicalCase(){
           TestDataUtil.dataValueMapCSData(); 
            Case cObjNT = TestDataUtil.createNonTechnicalCase();
            System.assert(cObjNT.Id !=null , 'Failed to create Non-Technical Case');
            System.assertEquals('Severity 1 - Critical', cObjNT.Priority);
            Account acc = TestDataUtil.createAccount();
            System.assert(acc.Id !=null , 'Failed to create Account');
            Entitlement en = TestDataUtil.createEntitlement(acc.Id);
            List<Entitlement> entitleCount= acc.Entitlements;
            system.assert(en.Id!=null,'Entitlement is not created');
            system.assert(entitleCount.size()!=1,'Entitlemet count is not 1');
            en.Support_Exception__c = true;
            update en;
                     
                      
            cObjNT.AccountId = acc.Id;
            update cObjNT;
            
           /* Contact con= [select Id,RPS_Status__c from Contact where Id=:cObjNT.ContactId];
            con.RPS_Status__c='Red';
            Update con;
            
            Test.startTest(); 
            con.Cleared_by_Compliance__c = true;
            Update con;
            Test.stopTest();*/
                        
            cObjNT.InboundEmailAlias__c=DataValueMap__c.getInstance('EHSP Escalations').Data_Value__c;
            update cObjNT;
            
            cObjNT.InboundEmailAlias__c=DataValueMap__c.getInstance('EHSP support').Data_Value__c;
            update cObjNT;
            test.starttest();
            case ca = new Case();
            ca.Subject ='Test Case';
            ca.AccountId = acc.Id;
            ca.contactId = cObjNT.ContactId;
            ca.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Non-Technical').getRecordTypeId(); 
            ca.Priority = 'Severity 2 - Major';
            insert ca;
            test.stoptest();
            
            System.assertEquals(acc.Id, cObjNT.AccountId);   
            System.assertEquals(acc.Special_Handling__c, cObjNT.Special_Handling__c);
        }
        static testMethod void nonTechnicalCase1(){
            TestDataUtil.dataValueMapCSData(); 
            Case cObjNT = TestDataUtil.createNonTechnicalCase();
            System.assert(cObjNT.Id !=null , 'Failed to create Non-Technical Case');
            System.assertEquals('Severity 1 - Critical', cObjNT.Priority);
            Account acc = TestDataUtil.createAccount();
            System.assert(acc.Id !=null , 'Failed to create Account');
            Entitlement en = TestDataUtil.createEntitlement(acc.Id);
            List<Entitlement> entitleCount= acc.Entitlements;
            system.assert(en.Id!=null,'Entitlement is not created');
            system.assert(entitleCount.size()!=1,'Entitlemet count is not 1');
            cObjNT.AccountId = acc.Id;
            update cObjNT;
            
            
            
            Contact con= [select Id,RPS_Status__c from Contact where Id=:cObjNT.ContactId];
            con.RPS_Status__c='Red';
            Update con;
            
            Test.startTest(); 
            con.Cleared_by_Compliance__c = true;
            Update con;
            Test.stopTest();
                        
              }
}