src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Versions__c</fullName>
        <label>Product Version</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Products__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Version</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KnowledgeArticle__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge Article</label>
    <pluralLabel>Knowledge Articles</pluralLabel>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/globalValueSets/Version.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0.1</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.3</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.4</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.8</fullName>
    </customValue>
    <customValue>
        <fullName>1.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.3</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.4</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.5</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.6</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.X</fullName>
    </customValue>
    <customValue>
        <fullName>1.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.5</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.9</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.10</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.14</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.15</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2.2</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <masterLabel>Version</masterLabel>
</GlobalValueSet>

src/classes/ArticleControllerTest.cls
@isTest(SeeAlldata=True)
public class ArticleControllerTest{
Static testMethod void Testmethod1()
{
//ApexPages.StandardSetController setCon;
Case cobj =new Case();
cobj.Subject= 'Test Subject';
cobj.Description= 'Test Description';
cobj.Products__c= 'Alpine Chorus for Pivotal Data Suite'; 
cobj.Versions__c= '6'; 
insert cobj;
String caseId = cobj.id;
    
ApexPages.currentPage().getParameters().put('sourceId', caseId);
ApexPages.currentPage().getParameters().put('sfdc.override', '1');
         
ApexPages.KnowledgeArticleVersionStandardController ctl = 
new ApexPages.KnowledgeArticleVersionStandardController(new KnowledgeArticle__kav());
         
new ArticleController(ctl);

//ApexPages.StandardController sc = new ApexPages.StandardController(cobj);
//ApexPages.KnowledgeArticleVersionStandardController ctl = new ApexPages.KnowledgeArticleVersionStandardController(cobj);
//ArticleController ac = new ArticleController();
//ac.ArticleController(ctl);
}
}