src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Service_Category__c</fullName>
        <label>Customer Services Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSR PWS Support</fullName>
                </value>
                <value>
                    <fullName>Entitlement</fullName>
                </value>
                <value>
                    <fullName>Internal Communications</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Pivnet</fullName>
                </value>
                <value>
                    <fullName>Pivotal Support Portal</fullName>
                </value>
                <value>
                    <fullName>Federation</fullName>
                    <isActive>false</isActive>
                    <label>Federation</label>
                </value>
                <value>
                    <fullName>Handoff</fullName>
                    <isActive>false</isActive>
                    <label>Handoff</label>
                </value>
                <value>
                    <fullName>KB Article Created</fullName>
                    <isActive>false</isActive>
                    <label>KB Article Created</label>
                </value>
                <value>
                    <fullName>MOD</fullName>
                    <isActive>false</isActive>
                    <label>MOD</label>
                </value>
                <value>
                    <fullName>Managed by CloudOps</fullName>
                    <isActive>false</isActive>
                    <label>Managed by CloudOps</label>
                </value>
                <value>
                    <fullName>POC</fullName>
                    <isActive>false</isActive>
                    <label>POC</label>
                </value>
                <value>
                    <fullName>Pivotal EH/SPClient</fullName>
                    <isActive>false</isActive>
                    <label>Pivotal EH/SPClient</label>
                </value>
                <value>
                    <fullName>SAB - Federation</fullName>
                    <isActive>false</isActive>
                    <label>SAB - Federation</label>
                </value>
                <value>
                    <fullName>Sales Opportunity</fullName>
                    <isActive>false</isActive>
                    <label>Sales Opportunity</label>
                </value>
                <value>
                    <fullName>Software</fullName>
                    <isActive>false</isActive>
                    <label>Software</label>
                </value>
                <value>
                    <fullName>Spam</fullName>
                    <isActive>false</isActive>
                    <label>Spam</label>
                </value>
                <value>
                    <fullName>Talkdesk</fullName>
                    <isActive>false</isActive>
                    <label>Talkdesk</label>
                </value>
                <value>
                    <fullName>Testing</fullName>
                    <isActive>false</isActive>
                    <label>Testing</label>
                </value>
                <value>
                    <fullName>VMWare</fullName>
                    <isActive>false</isActive>
                    <label>VMWare</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Service_Sub_Category_1__c</fullName>
        <description>This Picklist Field values are dependent on Customer Service Category</description>
        <label>Customer Services Sub Category 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Customer_Service_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Deletion</fullName>
                </value>
                <value>
                    <fullName>Account Questions</fullName>
                </value>
                <value>
                    <fullName>AskIT</fullName>
                </value>
                <value>
                    <fullName>Beta Tile Request</fullName>
                </value>
                <value>
                    <fullName>Billing Questions</fullName>
                </value>
                <value>
                    <fullName>Cannot locate PCN</fullName>
                </value>
                <value>
                    <fullName>Case Escalation</fullName>
                </value>
                <value>
                    <fullName>Case Owner Update</fullName>
                </value>
                <value>
                    <fullName>Case Requeue</fullName>
                </value>
                <value>
                    <fullName>Close User Account</fullName>
                </value>
                <value>
                    <fullName>Completed Onboarding AMER</fullName>
                </value>
                <value>
                    <fullName>Completed Onboarding APJ</fullName>
                </value>
                <value>
                    <fullName>Completed Onboarding EMEA</fullName>
                </value>
                <value>
                    <fullName>Completed Partner Onboarding</fullName>
                </value>
                <value>
                    <fullName>Customer Engineers</fullName>
                </value>
                <value>
                    <fullName>Customer Service Team</fullName>
                </value>
                <value>
                    <fullName>Documentation Team</fullName>
                </value>
                <value>
                    <fullName>DPL Check</fullName>
                </value>
                <value>
                    <fullName>Education Team</fullName>
                </value>
                <value>
                    <fullName>EH/SP</fullName>
                </value>
                <value>
                    <fullName>EOA/EOL Request</fullName>
                </value>
                <value>
                    <fullName>EOA Request</fullName>
                </value>
                <value>
                    <fullName>Expired Support Contract</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
                <value>
                    <fullName>Field Assist</fullName>
                </value>
                <value>
                    <fullName>Heightened Awareness</fullName>
                </value>
                <value>
                    <fullName>How to Submit Pivotal Support Request</fullName>
                </value>
                <value>
                    <fullName>How to Submit VMWare Requests</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Legal Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_KB_Article__c</fullName>
        <label>Related KB Article</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KB needed</fullName>
                    <label>KB Needed</label>
                </value>
                <value>
                    <fullName>KB/Doc exists</fullName>
                    <label>KB/Doc Exists</label>
                </value>
                <value>
                    <fullName>KB Not Applicable</fullName>
                    <isActive>false</isActive>
                    <label>KB Not Applicable</label>
                </value>
                <value>
                    <fullName>To be Filled Later</fullName>
                    <isActive>false</isActive>
                    <label>To be Filled Later</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/classes/PS_EmailMessageTriggerHandler_Test.cls
@isTest
public class PS_EmailMessageTriggerHandler_Test {
   //static TestDataUtil utilObj = new TestDataUtil();
    
    static testMethod void createEmailMessage(){
         TestDataUtil.dataValueMapCSData(); 
         Case cObj = TestDataUtil.createNonTechnicalCase();
         EmailMessage mail1 = TestDataUtil.createEmailMessage(cObj,'0',true,'testing@testData.com');
         System.assertEquals(mail1.ParentId,cObj.Id); 
       
         cObj.Customer_Service_Category__c='Entitlement';
         cObj.Customer_Service_Sub_Category_1__c='Cannot locate PCN';
         cObj.Related_KB_Article__c='KB Not Applicable';
         cObj.Status='Solved';
         update cObj;
       
        test.starttest();
         cObj.Status='Closed';
         //cObj.Products__c = 'CSR';
         update cObj;
         EmailMessage mail5 = TestDataUtil.createEmailMessage(cObj,'2',true,';testing@testData.com;');
         System.assertEquals(mail5.ParentId,cObj.Id);
         
         test.stoptest();
         
    }
        
    static testMethod void createEmailMessage1(){
         TestDataUtil.dataValueMapCSData(); 
         Case cObj = TestDataUtil.createNonTechnicalCase();
         EmailMessage mail1 = TestDataUtil.createEmailMessage(cObj,'0',true,'testing@testData.com');
         System.assertEquals(mail1.ParentId,cObj.Id); 
         EmailMessage mail2 = TestDataUtil.createEmailMessage(cObj,'0',false,';testing@testData.com;');
         System.assertEquals(mail2.ParentId,cObj.Id); 
         cObj.Status='Pending';
         update cObj;
    }
         
         static testMethod void createEmailMessage2(){
         TestDataUtil.dataValueMapCSData(); 
         Case cObj = TestDataUtil.createNonTechnicalCase();
             
         EmailMessage mail3 = TestDataUtil.createEmailMessage(cObj,'2',true,';testing@testData.com;'); 
         System.assertEquals(mail3.ParentId,cObj.Id); 
        
         cObj.Status='In Progress';
         update cObj;
  
         EmailMessage mail5 = TestDataUtil.createEmailMessage(cObj,'2',true,';testing@testData.com;'); 
         System.assertEquals(mail5.ParentId,cObj.Id); 
             
         cObj.Status='Pending';
         update cObj;

         EmailMessage mail4 = TestDataUtil.createEmailMessage(cObj,'2',true,';testing@testData.com;'); 
         System.assertEquals(mail4.ParentId,cObj.Id); 
             
         cObj.Customer_Service_Category__c='Entitlement';
         cObj.Customer_Service_Sub_Category_1__c='Cannot locate PCN';
         cObj.Related_KB_Article__c='KB Not Applicable';             
         cObj.Status='Solved';
         update cObj;
             
   }
         
         static testMethod void createEmailMessage3(){
         TestDataUtil.dataValueMapCSData(); 
         Case cObj = TestDataUtil.createNonTechnicalCase();
         EmailMessage mail4 = TestDataUtil.createEmailMessage(cObj,'2',true,';testing@testData.com;');
         System.assertEquals(mail4.ParentId,cObj.Id);
         
         EmailMessage mail6 = TestDataUtil.createEmailMessage(cObj,'2',true,';ondemand-support.scqa@pivotal.io;');
         EmailMessage mail7 = TestDataUtil.createEmailMessage(cObj,'2',false,';testing@testData.com;');

         System.assertEquals(mail7.ParentId,cObj.Id);
         system.debug('Email Message : '+ mail6.Toaddress);
         }
}