src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Products__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Component</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Component__c</fullName>
        <label>Sub Component</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Component__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Component</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Versions__c</fullName>
        <label>Product Version</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Products__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Version</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Component.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Access Control</fullName>
    </customValue>
    <customValue>
        <fullName>Ambari</fullName>
    </customValue>
    <customValue>
        <fullName>Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Apps ManagerV1</fullName>
        <label>Apps Manager</label>
    </customValue>
    <customValue>
        <fullName>AWS Service Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Azure Service Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Backup and Restore</fullName>
    </customValue>
    <customValue>
        <fullName>Blobstore</fullName>
    </customValue>
    <customValue>
        <fullName>BOSH (OSS)</fullName>
        <label>BOSH</label>
    </customValue>
    <customValue>
        <fullName>BOSH Backup &amp; Restore</fullName>
    </customValue>
    <customValue>
        <fullName>Buildpacks</fullName>
    </customValue>
    <customValue>
        <fullName>c2c Networking</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog &amp; Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog and Metadata</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog and Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog Brokers</fullName>
    </customValue>
    <customValue>
        <fullName>CF CLI</fullName>
    </customValue>
    <customValue>
        <fullName>CFCR</fullName>
    </customValue>
    <customValue>
        <fullName>ClamAV addon for PCF</fullName>
    </customValue>
    <customValue>
        <fullName>Client / Loading tools</fullName>
    </customValue>
    <customValue>
        <fullName>Client Access Methods</fullName>
    </customValue>
    <customValue>
        <fullName>Clients</fullName>
    </customValue>
    <customValue>
        <fullName>Client Tools</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Controller</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse</fullName>
    </customValue>
    <customValue>
        <fullName>CredHub Service Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Datanode</fullName>
    </customValue>
    <customValue>
        <fullName>DDL and Utility Statements</fullName>
    </customValue>
    <masterLabel>Component</masterLabel>
</GlobalValueSet>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sub_Component.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>.NET Client</fullName>
    </customValue>
    <customValue>
        <fullName>.NET Core</fullName>
    </customValue>
    <customValue>
        <fullName>Access Control</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts</fullName>
    </customValue>
    <customValue>
        <fullName>Admin REST API</fullName>
    </customValue>
    <customValue>
        <fullName>Advisors</fullName>
    </customValue>
    <customValue>
        <fullName>API</fullName>
    </customValue>
    <customValue>
        <fullName>API server</fullName>
    </customValue>
    <customValue>
        <fullName>App Usage</fullName>
    </customValue>
    <customValue>
        <fullName>Async Event Queue</fullName>
    </customValue>
    <customValue>
        <fullName>Authentication</fullName>
    </customValue>
    <customValue>
        <fullName>Autoscaler</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>AWS ELB</fullName>
    </customValue>
    <customValue>
        <fullName>AWS Service Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Azure</fullName>
    </customValue>
    <customValue>
        <fullName>Azure LB</fullName>
    </customValue>
    <customValue>
        <fullName>Azure Service Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Backing AppV2</fullName>
        <label>Backing App</label>
    </customValue>
    <customValue>
        <fullName>Backup and Restore</fullName>
    </customValue>
    <customValue>
        <fullName>BBR</fullName>
    </customValue>
    <customValue>
        <fullName>Binary</fullName>
    </customValue>
    <customValue>
        <fullName>Bosh</fullName>
    </customValue>
    <customValue>
        <fullName>Bosh DNS</fullName>
    </customValue>
    <customValue>
        <fullName>Brain</fullName>
    </customValue>
    <customValue>
        <fullName>Broker / Broker Worker</fullName>
    </customValue>
    <customValue>
        <fullName>Build</fullName>
    </customValue>
    <customValue>
        <fullName>Buildpack Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled Applications</fullName>
    </customValue>
    <customValue>
        <fullName>C++ Client</fullName>
    </customValue>
    <masterLabel>Sub Component</masterLabel>
</GlobalValueSet>

src/globalValueSets/Version.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0.1</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.3</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.4</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.8</fullName>
    </customValue>
    <customValue>
        <fullName>1.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.3</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.4</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.5</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.6</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.X</fullName>
    </customValue>
    <customValue>
        <fullName>1.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.5</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.9</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.10</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.14</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.15</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2.2</fullName>
    </customValue>
    <masterLabel>Version</masterLabel>
</GlobalValueSet>

src/classes/ArticleController.cls
/*******************************************************************************************************************
* Apex Class Name  : ArticleController 
* Version          : 1.0
* Created Date     : 08 August 2017
* Function         : class is used to auto populate values from case to artilce
* Modification Log :
*
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Karthik.A.S               08/03/2017            initial version
* --------------------------------------------------------------------------------------------------------------------
*******************************************************************************************************************/
public class ArticleController {
    
    public ArticleController(ApexPages.KnowledgeArticleVersionStandardController ctl) {
        SObject article = ctl.getRecord();   
        
        String sourceId = ctl.getSourceId(); 
        Case c = [select subject, description,Products__c,Versions__c,Component__c, Sub_Component__c,CaseNumber from Case where id=:sourceId];
        
        article.put('title', +c.subject);   
        article.put('Product2__c',c.Products__c); 
        article.put('Product_Version__c',c.Versions__c);
        article.put('Component__c',c.Component__c); 
        article.put('Sub_Component__c',c.Sub_Component__c);
        article.put('Article_Created_from_Case__c',c.CaseNumber);
    }
}