src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>Problem::Account / Dashboard</fullName>
                </value>
                <value>
                    <fullName>Problem::Defect</fullName>
                </value>
                <value>
                    <fullName>Problem::Documentation</fullName>
                </value>
                <value>
                    <fullName>Problem::Error</fullName>
                </value>
                <value>
                    <fullName>Problem::Implementation</fullName>
                </value>
                <value>
                    <fullName>Problem::Installation</fullName>
                </value>
                <value>
                    <fullName>Problem::Logging</fullName>
                </value>
                <value>
                    <fullName>Problem::Performance</fullName>
                </value>
                <value>
                    <fullName>Problem::Security</fullName>
                </value>
                <value>
                    <fullName>Problem::Technical Issues</fullName>
                </value>
                <value>
                    <fullName>Problem::Upgrade</fullName>
                </value>
                <value>
                    <fullName>Question::Contract / Maintenance / Licensing</fullName>
                </value>
                <value>
                    <fullName>Question::Partnership / Business Development</fullName>
                </value>
                <value>
                    <fullName>Question::Software Availability / Compatibility / Upgrades</fullName>
                </value>
                <value>
                    <fullName>Request::Customer Service Improvement</fullName>
                </value>
                <value>
                    <fullName>Request::Documentation Improvement</fullName>
                </value>
                <value>
                    <fullName>Request::Product Feature Improvement</fullName>
                </value>
                <value>
                    <fullName>Remote Access Meetings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_KB_Article__c</fullName>
        <label>Related KB Article</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KB needed</fullName>
                    <label>KB Needed</label>
                </value>
                <value>
                    <fullName>KB/Doc exists</fullName>
                    <label>KB/Doc Exists</label>
                </value>
                <value>
                    <fullName>KB Not Applicable</fullName>
                    <isActive>false</isActive>
                    <label>KB Not Applicable</label>
                </value>
                <value>
                    <fullName>To be Filled Later</fullName>
                    <isActive>false</isActive>
                    <label>To be Filled Later</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ISV</fullName>
                </value>
                <value>
                    <fullName>Escalation</fullName>
                </value>
                <value>
                    <fullName>3rd Party Software</fullName>
                </value>
                <value>
                    <fullName>Configuration</fullName>
                </value>
                <value>
                    <fullName>Customer Education</fullName>
                </value>
                <value>
                    <fullName>Defect Reported</fullName>
                </value>
                <value>
                    <fullName>Documentation</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Environment/Hardware</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information/Unresolved</fullName>
                </value>
                <value>
                    <fullName>Known Issue</fullName>
                </value>
                <value>
                    <fullName>Known Limitation</fullName>
                </value>
                <value>
                    <fullName>Not Entitled</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Product Fix</fullName>
                </value>
                <value>
                    <fullName>To Be Filled Later</fullName>
                </value>
                <value>
                    <fullName>Won't Fix</fullName>
                </value>
                <value>
                    <fullName>Workaround</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Steps_to_Resolve__c</fullName>
        <label>Steps to Resolve</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party/ISV Software Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Application Issue</fullName>
                </value>
                <value>
                    <fullName>Customer Environment Issue</fullName>
                </value>
                <value>
                    <fullName>Documented Limitation</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>Duplicate Issue (Tracked in Different Ticket)</fullName>
                </value>
                <value>
                    <fullName>Engineering Intervention Required</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Fix in Higher Version(Upgrade)</fullName>
                    <label>Fix in Higher Version (Upgrade)</label>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
                <value>
                    <fullName>Reconfig Network Configuration</fullName>
                    <label>Network Configuration</label>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Product Configuration</fullName>
                </value>
                <value>
                    <fullName>Reported Product Defect (pending fix)</fullName>
                </value>
                <value>
                    <fullName>VM/JVM Configuration</fullName>
                </value>
                <value>
                    <fullName>Workaround Provided</fullName>
                </value>
                <value>
                    <fullName>Works as Designed</fullName>
                </value>
                <value>
                    <fullName>Escalation Acknowledged</fullName>
                    <isActive>false</isActive>
                    <label>Escalation Acknowledged</label>
                </value>
                <value>
                    <fullName>Hardware Repair/Replacement</fullName>
                    <isActive>false</isActive>
                    <label>Hardware Repair/Replacement</label>
                </value>
                <value>
                    <fullName>Install hot fix</fullName>
                    <isActive>false</isActive>
                    <label>Install hot fix</label>
                </value>
                <value>
                    <fullName>Known Issue - No fix available yet</fullName>
                    <isActive>false</isActive>
                    <label>Known Issue - No fix available yet</label>
                </value>
                <value>
                    <fullName>Notification Acknowedged</fullName>
                    <isActive>false</isActive>
                    <label>Notification Acknowedged</label>
                </value>
                <value>
                    <fullName>Provide instructions</fullName>
                    <isActive>false</isActive>
                    <label>Provide instructions</label>
                </value>
                <value>
                    <fullName>Reconfig Pivotal software</fullName>
                    <isActive>false</isActive>
                    <label>Reconfig Pivotal software</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Versions__c</fullName>
        <label>Product Version</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Products__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Version</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Technical</fullName>
        <active>true</active>
        <businessProcess>Pivotal Support</businessProcess>
        <label>Technical</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BusinessHours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataValueMap__c.object
<CustomObject>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This cs is used to hold all the data value required to customize functionality</description>
    <label>Data Value Map</label>
</CustomObject>

src/objects/KnowledgeArticle__kav.object
<CustomObject>
    <fields>
        <fullName>Article_Author_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to User who authored the Knowledge Article.  May be a currently inactive legacy User.</description>
        <label>Article Author</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Knowledge_Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <description>2018 Service Cloud Implementation - KEEP This Product field.</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_KB_Article__c</fullName>
        <description>URL Link to another related article.</description>
        <inlineHelpText>URL Link to another related article.</inlineHelpText>
        <label>Related KB Article</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <inlineHelpText>What actions can the reader take to resolve or work around the described problem?</inlineHelpText>
        <label>Resolution</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Symptom__c</fullName>
        <description>Description of the symptoms or problem statement.</description>
        <inlineHelpText>Description of the symptoms or problem statement.</inlineHelpText>
        <label>Symptom</label>
        <length>100000</length>
        <type>Html</type>
    </fields>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge Article</label>
    <pluralLabel>Knowledge Articles</pluralLabel>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/globalValueSets/Version.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0.1</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.3</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.4</fullName>
    </customValue>
    <customValue>
        <fullName>1.0.8</fullName>
    </customValue>
    <customValue>
        <fullName>1.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.3</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.4</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.5</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.6</fullName>
    </customValue>
    <customValue>
        <fullName>1.1.X</fullName>
    </customValue>
    <customValue>
        <fullName>1.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.0</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.5</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.9</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.10</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.14</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.1.15</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2.1</fullName>
    </customValue>
    <customValue>
        <fullName>1.2.2.2</fullName>
    </customValue>
    <customValue>
        <fullName>2.4</fullName>
    </customValue>
    <masterLabel>Version</masterLabel>
</GlobalValueSet>

src/classes/PS_FeedItemComment_Test.cls
@isTest
public class PS_FeedItemComment_Test {
    /*static testMethod void  FeedItemCommentTriggerHandlerTest(){
    
       TestDataUtil.dataValueMapCSData();
       Case cObj = TestDataUtil.createTechnicalCase();
       system.assert(cObj.Id != null);
       FeedItem feed = TestDataUtil.createFeedItem(cObj.Id,'AllUsers');
       system.assert(feed.Id != null);
       Test.startTest();
           TestDataUtil.createPortalContact2();
           //system.assert(cont != null);
           
           Profile Prof = [Select id from profile where name ='Pivotal - Community Manager'];
        User usr = [SELECT Id,ProfileId
                  FROM User 
                  WHERE ProfileId = :Prof.Id limit 1];
          // System.debug('Contact id'+cont.id);
         //  User usr = [Select Id , ContactId , AccountId from User where isActive = true and Profile.Name='Pivotal - Community Manager'  limit 1];
           system.assert(usr != null,'Issue in creating User');
           Case cObj1;
            System.runAs(usr){
               cObj1 = TestDataUtil.createCaseByPortalUser(usr);
               System.assert(cObj1.Id != null,'Case not created');
            }
           cObj1.Status = 'Solved';
           update cObj1;
       Test.stopTest();

       System.runAs(usr){
           FeedItem ifeed = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           FeedItem ifeed2 = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           system.assert(ifeed.Id != null);
       }
    } */
    
    static testMethod void  addPostOnTechClosedCase(){
    TestDataUtil.dataValueMapCSData();
       Contact cont = TestDataUtil.createPortalContact2();
       system.assert(cont != null);
       User usr = [Select Id , contactId,AccountId from User where isActive = true and Profile.Name='Pivotal - Community Manager' limit 1];
       system.assert(usr != null,'Issue in creating User');
       Case cObj1;
        System.runAs(usr){
           cObj1 = TestDataUtil.createCaseByPortalUser(usr);
           system.assert(cObj1.Id != null);
        }
       Entitlement ent = TestDataUtil.createEntitlement(cObj1.AccountId);
       System.assert(ent!=null);
       cObj1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
       cObj1.EntitlementId = ent.Id;
         System.runAs(usr){
           FeedItem ifeed = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           system.assert(ifeed.Id != null);
       }
       cObj1.Status = 'Closed';
       
       update cObj1;
       
       System.runAs(usr){
           FeedItem ifeed = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           system.assert(ifeed.Id != null);
       }
      
 }   
    static testMethod void  addPostOnClosedCase(){
       TestDataUtil.dataValueMapCSData();
       Contact cont = TestDataUtil.createPortalContact2();
       system.assert(cont != null);
       User usr = [Select Id , ContactId , AccountId from User where isActive = true and Profile.Name='Pivotal - Community Manager' limit 1];
       system.assert(usr != null,'Issue in creating User');
       Case cObj1;
        System.runAs(usr){
           cObj1 = TestDataUtil.createCaseByPortalUser(usr);
           system.assert(cObj1.Id != null);
        }
       cObj1.Status = 'Closed';
       update cObj1;
       System.runAs(usr){
           FeedItem ifeed = TestDataUtil.createFeedItem(cObj1.Id,'AllUsers');
           system.assert(ifeed.Id != null);
       }
    }  
    
    
    static testMethod void  addPostonArticles(){
       TestDataUtil.dataValueMapCSData();
        KnowledgeArticle__kav bf = new KnowledgeArticle__kav();
        bf.Title = 'Test Articles';
        bf.UrlName = 'TestArticles';
        bf.Symptom__c = 'Test Articles';
        bf.Resolution__c = 'Test Articles';
        bf.Product2__c  = 'Alpine Chorus for Pivotal Data Suite';
        bf.Article_Author_Lookup__c= userInfo.getUserId();
        insert bf;
        System.assert(bf.Id!=null);
        String arId = [SELECT KnowledgeArticleId FROM KnowledgeArticle__kav WHERE Id = :bf.Id].KnowledgeArticleId;
        DatavalueMap__c  csDataList = DatavalueMap__c.getInstance('ArticleTypes');
        csDataList.Data_Value__c =arId.substring(0,3);
        update csDataList;
        System.assertEquals(arId.substring(0,3),csDataList.Data_Value__c , 'Not Match');
        KbManagement.PublishingService.publishArticle(arId, true);
        
        FeedItem ifeed = TestDataUtil.createFeedItem(arId,'AllUsers');
        system.assert(ifeed.Id != null);
        system.assertEquals(ifeed.ParentId ,arId);
        FeedComment cfeed = TestDataUtil.createfeedComment(ifeed.Id);
        system.assert(cfeed.Id != null);
    }
    static testMethod void profileRND(){
         TestDataUtil.dataValueMapCSData();
        User usr = [Select Id , ContactId  from User where isActive = true and Profile.Name='Pivotal - R&D'limit 1];
        system.assert(usr.Id != null);
        FeedItem feedpost=new FeedItem();
        Case cObj2 = new Case();
        Account acc1;
        acc1 = TestDataUtil.createAccount();
        acc1.OwnerId  = usr.Id;
        update acc1;
        BusinessHours busHrs = [select Id, Name FROM BusinessHours LIMIT 1];
        system.assert(busHrs.Id != null);
        
        Entitlement ent = TestDataUtil.createEntitlement(acc1.Id);
         System.runAs(usr)
        {
           Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.Email = 'Test@123.com';       
        con.BusinessHours__c = busHrs.Id;
        con.AccountId = (acc1 !=null ? acc1.Id : null);
        con.mailingcountry = 'India';
        insert con;
        System.assert(con.Id != null);
                    
        cObj2.Subject = 'Ignore Test Case';
        cObj2.Description ='Ignore Test Case creation via Test Class';
        cObj2.ContactId = con.Id;
        cObj2.AccountId = acc1.Id;
        cObj2.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical').getRecordTypeId();
        cObj2.EntitlementId = ent.Id;
        cObj2.Products__c='Alpine Chorus for Pivotal Data Suite';
        //cObj.Versions__c='2.4';
        cObj2.Priority='Severity 1 - Critical'; 
        cObj2.Resolution_Code__c='Not Entitled';
        cObj2.Related_KB_Article__c='KB Not Applicable';
        cObj2.Case_Type__c='Escalation';
        cObj2.Resolution__c='Test';
        cObj2.Steps_to_Resolve__c='Downgrade';
        cObj2.Resolution_Opportunity_Root_Cause__c='Customer Education';
        cObj2.Status ='Open';
        insert cObj2;
           system.assert(cObj2.Id != null);
        }
         System.runAs(usr)
        {
        feedpost = TestDataUtil.createFeedItem(cObj2.Id,'AllUsers');
        system.assert(feedpost.Id != null);
        }
        feedpost.Visibility='InternalUsers';
        update feedpost;
        update cObj2;
    }
}