src/objects/CategoryType__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This list determines whether a Product Service Category is a Product or a service</description>
    <label>Category Type</label>
</CustomObject>

src/objects/Channel__c.object
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country_Uplift__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Multiplier__c</fullName>
        <description>Multiplier applied for Services or Ed Services PSC products</description>
        <label>Service Multiplier</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Uplift_Multiplier__c</fullName>
        <label>Product Multiplier</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <description>Defines multiplier to List Price based on Sold To Country and  PSC
Formerly named County Uplift (API name Country_Uplift__c)</description>
    <label>Country Multiplier</label>
    <nameField>
        <label>Country Multiplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Multiplier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CountryMultiplierService.cls
public with sharing class CountryMultiplierService {
    public CountryMultiplierService() {}

    public CountryMultiplierInfo countryMultipliers(Zqu__Quote__c quote) {
        Decimal productMultiplier;
        Decimal serviceMultiplier;

        Id soldToContactId = quote.zqu__SoldToContact__c;
        Contact soldToContact = [SELECT Id,
                MailingCountryCode
        FROM Contact
        WHERE Id = :soldToContactId];

        String country = soldToContact.MailingCountryCode;

        List<Country_Uplift__c> countryUplifts = [SELECT Country_Code__c,
                Uplift_Multiplier__c,
                Service_Multiplier__c
        FROM Country_Uplift__c
        WHERE Country_Code__c = :country];

        productMultiplier = 1;
        productMultiplier.setScale(2);

        serviceMultiplier = 1;
        serviceMultiplier.setScale(2);

        if (countryUplifts.size() > 0) {
            Country_Uplift__c countryUplift = countryUplifts.get(0);
            productMultiplier = countryUplift.Uplift_Multiplier__c;
            serviceMultiplier = countryUplift.Service_Multiplier__c;

            if (quote.Channel__c != 'Pivotal Direct' && quote.Channel__c != 'Federation') {
                serviceMultiplier = 1;
            }
        }

        return new CountryMultiplierInfo(productMultiplier, serviceMultiplier);
    }

    public Decimal multiplier(String productServiceCategory, CountryMultiplierInfo multiplierInfo) {
        CategoryType__c categoryType = CategoryType__c.getInstance(productServiceCategory);

        if(categoryType == null) {
            throw new CountryMultiplierServiceException('Category Type of ' + productServiceCategory + ' not found in the Category Type Custom Setting');
        } else if (categoryType.Type__c == 'Service') {
            return multiplierInfo.ServiceMultiplier;
        } else {
            return multiplierInfo.ProductMultiplier;
        }
    }

    public class CountryMultiplierServiceException extends Exception {}
}