src/objects/Certification__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Product_Version__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Product Version</label>
        <referenceTo>Partner_Product_Version__c</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pivotal_Product_Version__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pivotal Product Version</label>
        <referenceTo>Pivotal_Integrated_Product_Version__c</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pivotal_Product_f__c</fullName>
        <description>This field links to the Pivotal Product.

Note the complicated formula which allowed the name to be properly displayed.</description>
        <formula>HYPERLINK( '/' &amp; Pivotal_Product_Version__r.Product_Name_Piv__r.Name,'') &amp; HYPERLINK( '/' &amp; Pivotal_Product_Version__r.Product_Name_Piv__c, Pivotal_Product_Version__r.Product_Name_Piv__r.Name, '_parent')</formula>
        <label>Pivotal Product</label>
        <type>Text</type>
    </fields>
    <description>Record of a Partner's certification.</description>
    <label>Certification</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Certification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Certification_Test__c.object
<CustomObject>
    <fields>
        <fullName>Certification__c</fullName>
        <description>Parent record of the Certification Test. Displays as the Certification__r.Name ie the "Certification ID" field.</description>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>Certification Tests</relationshipLabel>
        <relationshipName>Certification_Tests1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Captures details around the related testing around a certification.

Not all certifications have to have a certification test record.</description>
    <label>Certification Test</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Certification Test ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certification Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Product__c.object
<CustomObject>
    <description>Used to keep track of all products (both Pivotal's and Partner's) that interoperate with other products.</description>
    <label>Partner Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Product_Version__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name_Partner__c</fullName>
        <label>Product Name</label>
        <referenceTo>Partner_Product__c</referenceTo>
        <relationshipLabel>Product Versions</relationshipLabel>
        <relationshipName>Partner_Product_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Tracks the versions of a product</description>
    <label>Partner Product Version</label>
    <nameField>
        <label>Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Product Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pivotal_Integrated_Product__c.object
<CustomObject>
    <description>Pivotal products that have been/are capable of integrated with other products.</description>
    <label>Pivotal Integrated Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pivotal Integrated Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pivotal_Integrated_Product_Version__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name_Piv__c</fullName>
        <label>Product Name</label>
        <referenceTo>Pivotal_Integrated_Product__c</referenceTo>
        <relationshipLabel>Product Versions</relationshipLabel>
        <relationshipName>Pivotal_Integrated_Product_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pivotal Integrated Product Version</label>
    <nameField>
        <label>Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pivotal Integrated Product Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/certTestExtension.cls
public class certTestExtension {
    /**
    *    certTestExtension() is the extension for /apex/newCertTest, new record page for a certification test. 
    *    It shows the name of the certification record for which the test record is being created
    *    to prevent confusion/enhance the user experience.
    *    A user can only navigate to this page from a certification detail page so the id of the
    *    certification is passed through the URL ie '/apex/newCertTest?certId=a0xJ0000007SCBg'.
    *    If a user navigates to the url without an id param, then they will see an error message.
    *
    *
    */
    public final ApexPages.standardController controller;
    public String certName {get; set;}
    public Id certId {get; set;}
    public final Certification_Test__c certTest;
    public Boolean showForm {get; set;}    //boolean that determines if the error message (no id param in url) is displayed or not

    /**
    *    certTestExtension() is the constructor for the extension. 
    *    @param the standard controller 
    *    
    */
    public certTestExtension(ApexPages.StandardController stdcontroller) {
        this.controller = stdcontroller;
        this.certTest = (Certification_Test__c) stdcontroller.getRecord();
        //check if URL has id params and set the Certification Name
        if(ApexPages.currentPage().getParameters().get('certId') != null) {
            certId = Id.valueOf(ApexPages.currentPage().getParameters().get('certId'));
            certTest.Certification__c = certID;
            certName = concatCertName();
            showForm = true;       
        } else {    //no id params passed
            showForm = false;
        }
        
    }

    /*
    *    concatCertName() is a helper method that concantenates the Certification Name from a Certification record
    *    NOTE: Pivotal_Product_Version__r.Product_Name_Piv__r.Name is used to get the Pivotal Product name instead of
    *    directly using Pivotal_Product_f__c because of the escaped html characters from the nature of the field. Same for Partner Product name.
    */

    public String concatCertName() {
        Certification__c cert = [    SELECT Pivotal_Product_Version__r.Product_Name_Piv__r.Name, Partner_Product_Version__r.Product_Name_Partner__r.Name, Pivotal_Product_Version__r.Name, Partner_Product_Version__r.Name
                                     FROM Certification__c
                                     WHERE Id =: certId];
        return cert.Pivotal_Product_Version__r.Product_Name_Piv__r.Name + ' ' + cert.Pivotal_Product_Version__r.Name + ' - ' + cert.Partner_Product_Version__r.Product_Name_Partner__r.Name + ' ' + cert.Partner_Product_Version__r.Name;
    
    }
    /*
    *    cancel_record() returns the user to the previous page (certification record detail page).
    *
    *
    */
    public pageReference cancel_record() {
        PageReference resultPage = new PageReference('/'+ certId);
        resultPage.setRedirect(true);
        return resultPage;   
    }
}