src/objects/CNS_Region__c.object
<CustomObject>
    <fields>
        <fullName>CNS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CNS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CNS_Rep_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER West</fullName>
                </value>
                <value>
                    <fullName>AMER Fed</fullName>
                </value>
                <value>
                    <fullName>AMER ISR</fullName>
                </value>
                <value>
                    <fullName>AMER Labs</fullName>
                </value>
                <value>
                    <fullName>AMER PDE</fullName>
                </value>
                <value>
                    <fullName>AMER Data Sales</fullName>
                </value>
                <value>
                    <fullName>AMER Sub Renewals</fullName>
                </value>
                <value>
                    <fullName>AMER Other</fullName>
                </value>
                <value>
                    <fullName>APJ Australia New Zealand</fullName>
                </value>
                <value>
                    <fullName>APJ Greater China</fullName>
                </value>
                <value>
                    <fullName>APJ India</fullName>
                </value>
                <value>
                    <fullName>APJ ISR</fullName>
                </value>
                <value>
                    <fullName>APJ Japan</fullName>
                </value>
                <value>
                    <fullName>APJ Korea</fullName>
                </value>
                <value>
                    <fullName>APJ Other</fullName>
                </value>
                <value>
                    <fullName>APJ South Asia</fullName>
                </value>
                <value>
                    <fullName>APJ Southeast Asia</fullName>
                </value>
                <value>
                    <fullName>Bay Area</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Central North</fullName>
                </value>
                <value>
                    <fullName>Central West</fullName>
                </value>
                <value>
                    <fullName>EMEA Central</fullName>
                </value>
                <value>
                    <fullName>EMEA France &amp; S Europe</fullName>
                </value>
                <value>
                    <fullName>EMEA ISR</fullName>
                </value>
                <value>
                    <fullName>EMEA Labs</fullName>
                </value>
                <value>
                    <fullName>EMEA MEA</fullName>
                </value>
                <value>
                    <fullName>EMEA Other</fullName>
                </value>
                <value>
                    <fullName>EMEA UKI</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Labs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CNS Region</label>
    <nameField>
        <displayFormat>C-{00}</displayFormat>
        <label>CNS Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNS Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Is_ISR__c</fullName>
        <description>This is the opportunity owner's region - from their user record.  (A hidden field to find out of the Opp owner is an ISR rep - this field will be used in the approval process)</description>
        <formula>TEXT(Owner.Region__c)</formula>
        <label>Owner Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Concat__c</fullName>
        <label>Product Concat</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <businessProcess>Pivotal</businessProcess>
        <description>Use this record type for Services products only</description>
        <label>Services</label>
        
    </recordTypes>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>PricebookEntry.Product2.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Portfolio__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.Report_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Portfolio</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <inlineHelpText>This field is ready only, please contact the system administrator to change it.</inlineHelpText>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Area__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AMER Central</fullName>
                </value>
                <value>
                    <fullName>AMER Data Sales</fullName>
                    <color>#9999FF</color>
                    <label>AMER Data Sales</label>
                </value>
                <value>
                    <fullName>AMER Dell Synergy</fullName>
                </value>
                <value>
                    <fullName>AMER East</fullName>
                </value>
                <value>
                    <fullName>AMER ISR</fullName>
                    <color>#66FFFF</color>
                    <label>AMER ISR</label>
                </value>
                <value>
                    <fullName>AMER Other</fullName>
                    <color>#DDDDDD</color>
                    <label>AMER Other</label>
                </value>
                <value>
                    <fullName>AMER PDE</fullName>
                    <color>#FF9966</color>
                    <label>AMER PDE</label>
                </value>
                <value>
                    <fullName>AMER South</fullName>
                </value>
                <value>
                    <fullName>AMER Sub Renewals</fullName>
                    <color>#FFFF66</color>
                    <label>AMER Sub Renewals</label>
                </value>
                <value>
                    <fullName>AMER-Support</fullName>
                </value>
                <value>
                    <fullName>AMER VMware Synergy</fullName>
                </value>
                <value>
                    <fullName>AMER West</fullName>
                    <color>#A53711</color>
                    <label>AMER West</label>
                </value>
                <value>
                    <fullName>APJ Australia New Zealand</fullName>
                    <color>#990000</color>
                    <label>APJ Australia New Zealand</label>
                </value>
                <value>
                    <fullName>APJ Greater China</fullName>
                    <color>#419249</color>
                    <label>APJ Greater China</label>
                </value>
                <value>
                    <fullName>APJ India</fullName>
                </value>
                <value>
                    <fullName>APJ ISR</fullName>
                    <color>#FF9900</color>
                    <label>APJ ISR</label>
                </value>
                <value>
                    <fullName>APJ Japan</fullName>
                    <color>#641CCF</color>
                    <label>APJ Japan</label>
                </value>
                <value>
                    <fullName>APJ Korea</fullName>
                    <color>#F96FB7</color>
                    <label>APJ Korea</label>
                </value>
                <value>
                    <fullName>APJ Other</fullName>
                    <color>#66E9BD</color>
                    <label>APJ Other</label>
                </value>
                <value>
                    <fullName>APJ South Asia</fullName>
                </value>
                <value>
                    <fullName>APJ Southeast Asia</fullName>
                    <color>#2F5D85</color>
                    <label>APJ Southeast Asia</label>
                </value>
                <value>
                    <fullName>APJ-Support</fullName>
                </value>
                <value>
                    <fullName>APJ VMWare Synergy</fullName>
                </value>
                <value>
                    <fullName>Bay Area</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                    <color>#0B24BE</color>
                    <label>Canada</label>
                </value>
                <value>
                    <fullName>Central North</fullName>
                    <color>#419249</color>
                    <label>Central North</label>
                </value>
                <value>
                    <fullName>Central West</fullName>
                </value>
                <value>
                    <fullName>Chatter Only</fullName>
                    <color>#663333</color>
                    <label>Chatter Only</label>
                </value>
                <value>
                    <fullName>EMEA - Central</fullName>
                </value>
                <value>
                    <fullName>EMEA Central FSI/Telco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OpportunityLineItemTriggerHandler.cls
public with sharing class OpportunityLineItemTriggerHandler extends TriggerHandler {
    public OpportunityLineItemTriggerHandler() {
    }

    /* Context Overrides */

    protected override void beforeInsert() {
        updateOpportunityTeamMembers();
    }

    protected override void beforeUpdate() {
        updateOpportunityTeamMembers();
    }

    protected override void afterInsert() {
         updateProductConcatOnOpp();
    }

    protected override void afterDelete() {
        updateProductConcatOnOpp();
    }

    /* Private Methods */

    private void updateOpportunityTeamMembers() {
        List<Id> oppIds = new List<Id>();
        List<String> oppRegions = new List<String>();

        for (OpportunityLineItem oli : (List<OpportunityLineItem>) Trigger.new) {
            if (oli.Product_Portfolio__c == 'PaaS' || oli.Product_Portfolio__c == 'PaaS - Edu' || oli.Product_Portfolio__c == 'PaaS - Eng Director' || oli.Product_Portfolio__c == 'PaaS - Services' || oli.Product_Portfolio__c == 'Agile - Tx') {
                oppIds.add(oli.OpportunityId);
            }
        }

        List<Opportunity> matchingOpps = [SELECT Id, OwnerId, Is_ISR__c FROM Opportunity WHERE Id IN :oppIds];
        for (Opportunity opp : matchingOpps) {
            // added null check
            if (opp.Is_ISR__c!=null)
                oppRegions.add(opp.Is_ISR__c);
        }


        if (matchingOpps.size() > 0 && oppRegions.size() > 0) {
            List<CNS_Region__c> cnsRegionList = [SELECT Id, CNS_Rep__r.Id, Region__c from CNS_Region__c where Region__c IN :oppRegions and CNS_Rep__r.isactive = true];
            List<OpportunityTeamMember> oppTeam = createOpportunityTeamMembers(matchingOpps, cnsRegionList);

            if (oppTeam.size() > 0) {
                insert oppTeam;
            }
        }
    }

    private List<OpportunityTeamMember> createOpportunityTeamMembers(List<Opportunity> matchingOpps, List<CNS_Region__c> cnsRegionList) {
        List<OpportunityTeamMember> oppTeam = new List<OpportunityTeamMember>();

        for (Opportunity opp : matchingOpps) {
            for (CNS_Region__c cnsRegion : cnsRegionList) {
                if (opp.OwnerId != cnsRegion.CNS_Rep__r.Id && opp.Is_ISR__c == cnsRegion.Region__c && (opp.OwnerId == UserInfo.getUserId() || UserInfo.getProfileId() == '00eU0000000sKBKIA2')) {
                    OpportunityTeamMember otm = new OpportunityTeamMember();
                    otm.OpportunityId = opp.Id;
                    otm.UserId = cnsRegion.CNS_Rep__r.Id;
                    otm.TeamMemberRole = 'Cloud Native Sales Rep';
                    otm.OpportunityAccessLevel = 'Edit';
                    oppTeam.add(otm);
                }
            }
        }

        return oppTeam;
    }

    private void updateProductConcatOnOpp() {
        List<Id> oppIds = new List<Id>();
        List<OpportunityLineItem> oppLineItems = new List<OpportunityLineItem>();

        if(Trigger.isInsert) {
            oppLineItems = (List<OpportunityLineItem>) Trigger.new;
        } else if(Trigger.isDelete) {
            oppLineItems = (List<OpportunityLineItem>) Trigger.old;
        }

        for (OpportunityLineItem oppLine : oppLineItems) {
            oppIds.add(oppLine.OpportunityId);
        }

        Map<Id, Opportunity> oppsToConcat = new Map<Id, Opportunity>([SELECT Id, Product_Concat__c, (SELECT Id, Product_Name__c FROM OpportunityLineItems) FROM Opportunity WHERE Id IN :oppIds]);

        for(Opportunity opp : oppsToConcat.values()) {
            opp.Product_Concat__c = null;

            for(OpportunityLineItem oppLine : opp.OpportunityLineItems) {
                if (String.isEmpty(opp.Product_Concat__c)) {
                    opp.Product_Concat__c = oppLine.Product_Name__c;
                } else if (!opp.Product_Concat__c.contains(oppLine.Product_Name__c)) {
                    opp.Product_Concat__c += '; ' + oppLine.Product_Name__c;
                }
            }
        }

        update oppsToConcat.values();
    }
}