src/objects/Community_MenuItems__mdt.object
<CustomObject>
    <fields>
        <fullName>Menu_Label__c</fullName>
        <label>Menu Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisibleTo__c</fullName>
        <inlineHelpText>Populate Profile Ids (18digit)</inlineHelpText>
        <label>VisibleTo</label>
        <type>TextArea</type>
    </fields>
    <description>Used to control the tab in portal community</description>
    <label>Community MenuItem</label>
    <pluralLabel>Community MenuItems</pluralLabel>
</CustomObject>

src/classes/PS_communityUIController.cls
/*******************************************************************************************************************
* Apex Class Name  : PS_communityUIController
* Test Class Name  : PS_communityUIController_TC
* Version          : 1.0
* Function         : Class is used for Community UI
* Modification Log :
*
* Developer                        Date                       Description
* ------------------------------------------------------------------------------------------------------------------
* Hemavathi NM                     10/06/2017              Intial version
* --------------------------------------------------------------------------------------------------------------------
*******************************************************************************************************************/
public with sharing class PS_communityUIController{
    @AuraEnabled
    //Used to update Menu List in Community
    Public static List<Community_MenuItems__mdt> getMenuList()
    {
         String profileId = String.valueOf(userInfo.getProfileId()).SubString(0,15);
         list<Community_MenuItems__mdt> menuItemL = new List<Community_MenuItems__mdt>();
         for(Community_MenuItems__mdt menu: [select DeveloperName,Id,Menu_Label__c,URL__c,Object_Name__c,VisibleTo__c,Sequence_Number__c from Community_MenuItems__mdt order by Sequence_Number__c LIMIT 1000]){
              if(menu.VisibleTo__c !=null&& menu.VisibleTo__c.contains(profileId)){menuItemL.add(menu);}     
          }
          return menuItemL;
       }
}