src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Best_Method_of_Contact__c</fullName>
        <description>This field is used to store Preferred method of contact</description>
        <label>Best Method of Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                    <isActive>false</isActive>
                    <label>Portal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChangedToL2__c</fullName>
        <label>Changed to L2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Profile Changed to L2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Time_Login__c</fullName>
        <label>First Time Login</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pivotal_Customer_Number__c</fullName>
        <description>This field is only used when a customer self-registers on the Portal.  This is a request to be associated to a particular PCN.</description>
        <label>Pivotal Customer Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Selection2__c</fullName>
        <label>Product Selection</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TermsAndConditions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for Service Cloud Community...contacts should be selecting during registration.</description>
        <label>Terms &amp; Conditions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <defaultValue>"America/Los_Angeles"</defaultValue>
        <label>Time zone where you work</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pacific/Enderbury</fullName>
                </value>
                <value>
                    <fullName>Pacific/Tongatapu</fullName>
                </value>
                <value>
                    <fullName>Pacific/Chatham</fullName>
                </value>
                <value>
                    <fullName>Asia/Kamchatka</fullName>
                </value>
                <value>
                    <fullName>Pacific/Auckland</fullName>
                </value>
                <value>
                    <fullName>Pacific/Fiji</fullName>
                </value>
                <value>
                    <fullName>Pacific/Guadalcanal</fullName>
                </value>
                <value>
                    <fullName>Pacific/Norfolk</fullName>
                </value>
                <value>
                    <fullName>Australia/Lord_Howe</fullName>
                </value>
                <value>
                    <fullName>Australia/Brisbane</fullName>
                </value>
                <value>
                    <fullName>Australia/Sydney</fullName>
                </value>
                <value>
                    <fullName>Australia/Adelaide</fullName>
                </value>
                <value>
                    <fullName>Australia/Darwin</fullName>
                </value>
                <value>
                    <fullName>Asia/Seoul</fullName>
                </value>
                <value>
                    <fullName>Asia/Tokyo</fullName>
                </value>
                <value>
                    <fullName>Asia/Hong_Kong</fullName>
                </value>
                <value>
                    <fullName>Asia/Kuala_Lumpur</fullName>
                </value>
                <value>
                    <fullName>Asia/Manila</fullName>
                </value>
                <value>
                    <fullName>Asia/Shanghai</fullName>
                </value>
                <value>
                    <fullName>Asia/Singapore</fullName>
                </value>
                <value>
                    <fullName>Asia/Taipei</fullName>
                </value>
                <value>
                    <fullName>Australia/Perth</fullName>
                </value>
                <value>
                    <fullName>Asia/Bangkok</fullName>
                </value>
                <value>
                    <fullName>Asia/Ho_Chi_Minh</fullName>
                </value>
                <value>
                    <fullName>Asia/Jakarta</fullName>
                </value>
                <value>
                    <fullName>Asia/Rangoon</fullName>
                </value>
                <value>
                    <fullName>Asia/Dhaka</fullName>
                </value>
                <value>
                    <fullName>Asia/Kathmandu</fullName>
                </value>
                <value>
                    <fullName>Asia/Colombo</fullName>
                </value>
                <value>
                    <fullName>Asia/Kolkata</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/classes/ContactUpdateApexController.cls
/******************************************************************************************************
* Apex Class Name  : ContactUpdateApexController
* Version          : 1.0
* Created Date     : 8 March 2017
* Function         : This Class has an invocable method which is used to Update the Contact Details that 
                     come from the Login Flow
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
Soham Banerjee              03/08/2018                Intial version
*******************************************************************************************************/
public without sharing class ContactUpdateApexController {
    @InvocableMethod
/***
Method Name : updateContact
Purpose : invocable method which is used to Update the Contact Details that come from the Login Flow
***/
    public static void updateContact(List<String> fieldValues){
        System.debug('fieldValues: ' + fieldValues);
        Contact contactRecord = new Contact();
        for(String fieldValuePair : fieldValues[0].split('~')){
            if(('Id').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                contactRecord.Id = fieldValuePair.substringAfter('=');
            }
            else if(('Best_Method_of_Contact__c').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                contactRecord.Best_Method_of_Contact__c = fieldValuePair.substringAfter('=');
            }
            else if(('Company__c').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                contactRecord.Company__c = fieldValuePair.substringAfter('=');
            }
            else if(('Phone').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                contactRecord.Phone = fieldValuePair.substringAfter('=').remove(',');
            }
            else if(('Product_Selection2__c').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                contactRecord.Product_Selection2__c = fieldValuePair.substringAfter('=');
            }
            else if(('TermsAndConditions__c').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                if(fieldValuePair.substringAfter('=') == 'true')
                    contactRecord.TermsAndConditions__c = true;
            }
            else if(('Time_Zone__c').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                contactRecord.Time_Zone__c = fieldValuePair.substringAfter('=');
            }
            else if(('Title').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                contactRecord.Title = fieldValuePair.substringAfter('=');
            }
            else if(('MailingCountryCode').equalsIgnoreCase(fieldValuePair.substringBefore('='))){
                contactRecord.MailingCountryCode = fieldValuePair.substringAfter('=');
            }
            else if(('PCN').equalsIgnoreCase(fieldValuePair.substringBefore('=')) && 
                    String.isNotEmpty(fieldValuePair.substringAfter('='))){
                contactRecord.Pivotal_Customer_Number__c = fieldValuePair.substringAfter('=');
            }
            else if(('AlreadyL2').equalsIgnoreCase(fieldValuePair.substringBefore('=')) && 
                    ('').equalsIgnoreCase(fieldValuePair.substringAfter('='))){
                contactRecord.ChangedToL2__c = 'Profile Changed to L2';
            }
        }
        try{
            if(contactRecord.Id != NULL){
                contactRecord.First_Time_Login__c = 'No';
                CheckRecursive.checkContact = false;
                update contactRecord;
            }
        }
        catch(Exception e){
            ErrorLog.CreateER(e);//Exception captured in Utility Class Errorlog
        }
    }
}