src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will Be Used to select key point contact</description>
        <label>Add / Manage Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DPL_Status__c</fullName>
        <formula>IF(
   ISPICKVAL( Export_Status__c, "Denied"), "Restricted",
   
   IF
     (ISPICKVAL( Export_Status__c, "Cleared"),"Unrestricted",

     IF(
        AND(
            OR(
               ISPICKVAL( Export_Status__c, "In Progress"),
               ISPICKVAL( Export_Status__c, "Not Started")
              ),
            OR(
               OR(
                  RPS_Status__c = "Red", 
                  RPS_Status__c = "Double Red",
                  RPS_Status__c = "Triple Red"
                 ),
                AND(
                   RPS_Status__c = "Risk Country",
                   Embargo_Country__c = TRUE
                   ),
                Embargo_Country__c = TRUE
               )
            ), 
            "Restricted",
            "Unrestricted"
      )
    )
  )</formula>
        <label>DPL Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Portal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To enable contact as the community user</inlineHelpText>
        <label>Open Cases for Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interact_with_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Assign User L1 Profile Permissions</description>
        <inlineHelpText>Assign User L1 Profile Permissions</inlineHelpText>
        <label>Interact with Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_of_Creation__c</fullName>
        <label>Source of Creation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce UI</fullName>
                    <default>true</default>
                    <label>Salesforce UI</label>
                </value>
                <value>
                    <fullName>JIT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UAA_ID__c</fullName>
        <label>UAA ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Account_Cases__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View all Cases for Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DataValueMap__c.object
<CustomObject>
    <fields>
        <fullName>Data_Value__c</fullName>
        <label>Data Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This cs is used to hold all the data value required to customize functionality</description>
    <label>Data Value Map</label>
</CustomObject>

src/objects/PortalUserCreationMap__c.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>PortalUserCreationMap</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Source_of_Creation__c</fullName>
        <formula>TEXT(Contact.Source_of_Creation__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source of Creation</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UAAJITRegHandlerApexController.cls
//This class provides logic for inbound just-in-time provisioning of single sign-on users in your Salesforce organization.
global without sharing class UAAJITRegHandlerApexController implements Auth.SamlJitHandler {
    private class JitException extends Exception{}
    Contact conRecord = new Contact();
    
    /***************************************************************************************************** 
    Method Name:        handleUserForUAA
    @return  :          User
    Description:        UAA Just In Time provisioning
    Added By:           Accenture - SB
    Modified By:        Changes: 
    Accenture - SB      This method queries the User Object with the data from the FederationIdentifier
    ******************************************************************************************************/
    private User handleUserForUAA(Map<String, String> attributes, String federationIdentifier) {
        if(attributes.containsKey('User.FederationIdentifier')){
            federationIdentifier = attributes.get('User.FederationIdentifier');
        }
        if(federationIdentifier != NULL){
            try{
                List<User> userRecordList = [SELECT Id, UserName, Email, FederationIdentifier
                                             FROM User
                                             WHERE FederationIdentifier LIKE :federationIdentifier
                                             LIMIT 1];
                if(userRecordList.isEmpty() && conRecord != NULL){
                    String queryString = 'SELECT Id, FirstName, LastName, Email, Interact_with_Community__c, ' +
                                                'Enable_Portal_User__c, View_Account_Cases__c, Customer_Admin__c, ' +
                                                'AccountId, DPL_Status__c, ';
                    for(PortalUserCreationMap__c cSFields : PortalUserCreationMap__c.getAll().Values())
                    {
                        if(!queryString.containsIgnoreCase(cSFields.Source__c + ', '))
                            queryString += cSFields.Source__c + ', ';
                    }
                    queryString = queryString.removeEnd(', ');
                    String contactRecordId = conRecord.Id;
                    queryString += ' FROM Contact ' +
                                   'WHERE Id = :contactRecordId';
                    System.debug('queryString: ' + queryString);
                    List<Contact> conList = Database.query(queryString);
                    conRecord = conList[0];
                    
                    User usrRecord = new User();
                    for(PortalUserCreationMap__c cSFields : PortalUserCreationMap__c.getAll().Values())
                    {
                        usrRecord.put(cSFields.Name,conRecord.get(cSFields.Source__c));
                    }
                    usrRecord.EmailEncodingKey = 'ISO-8859-1';
                    String keyToNickName = conRecord.LastName + conRecord.Email + conRecord.FirstName;
                    String Nickname = PS_ContactTriggerHandler.generateRandomString(12, keyToNickName);
                    usrRecord.Alias = PS_ContactTriggerHandler.generateRandomString(6, Nickname);
                    usrRecord.CommunityNickname = Nickname;
                    usrRecord.ProfileId = DataValueMap__c.getInstance('PortalRegisteredUserId').Data_Value__c;
                    usrRecord.TimeZoneSidKey = 'America/Los_Angeles';
                    usrRecord.LanguageLocaleKey = 'en_US';
                    usrRecord.LocaleSidKey = 'en_US';
                    if(conRecord.DPL_Status__c != 'Restricted')
                    {   
                        usrRecord.isActive = true;
                    }
                    insert usrRecord;
                    
                    conRecord.Interact_with_Community__c = true;
                    update conRecord;
                    
                    return usrRecord;
                }
                else if(userRecordList[0].Email != userRecordList[0].FederationIdentifier){
                    ErrorLog.CreateER(new JitException('Email and FederationId does not match in Salesforce. Contact the CSR for further assistance.'));
                }
                else{
                    userRecordList[0].FederationIdentifier = federationIdentifier;
                    userRecordList[0].Email = federationIdentifier;
                    return userRecordList[0];
                }
                return NULL;
            }catch(Exception e){
                ErrorLog.CreateER(e);//Exception captured in Utility Class Errorlog
                return NULL;
            }
        }
        return NULL;
    }

    /***************************************************************************************************** 
    Method Name:        handleContactForUAA
    @return  :          User
    Description:        UAA Just In Time provisioning
    Added By:           Accenture - SB
    Modified By:        Changes: 
    Accenture - SB      This method queries the Contact object with the data from the email attribute
    ******************************************************************************************************/
    private void handleContactForUAA(Map<String, String> attributes, String federationIdentifier) {
        List<Contact> conList = [SELECT Id, Email, LastModifiedDate
                                 FROM Contact 
                                 WHERE Email LIKE :attributes.get('email')
                                 ORDER By LastModifiedDate DESC
                                 LIMIT 1];
        if(conList.isEmpty()){
            conRecord.AccountId = DataValueMap__c.getInstance('RegisteredAccount').Data_Value__c;
            conRecord.Email = attributes.get('User.FederationIdentifier');
            //conRecord.Email = federationIdentifier;
            /*if(attributes.containsKey('User.FirstName'))
                conRecord.FirstName = attributes.get('User.FirstName').substringBefore('@');
            else if (attributes.containsKey('name'))
                conRecord.FirstName = attributes.get('name').substringBefore('@');
            if(attributes.containsKey('User.LastName'))
                conRecord.LastName = attributes.get('User.LastName').substringBefore('@');
            else if (attributes.containsKey('name'))
                conRecord.LastName = attributes.get('name').substringBefore('@');*/
            if(attributes.containsKey('Contact.FirstName'))
                conRecord.FirstName = attributes.get('Contact.FirstName');
            else if (attributes.containsKey('name'))
                conRecord.FirstName = attributes.get('name').substringBefore('@');
            if(attributes.containsKey('Contact.LastName'))
                conRecord.LastName = attributes.get('Contact.LastName');
            else if (attributes.containsKey('name'))
                conRecord.LastName = attributes.get('name').substringBefore('@');
            conRecord.Interact_with_Community__c = true;
            conRecord.UAA_ID__c = attributes.get('User.FederationIdentifier');
            //conRecord.UAA_ID__c = federationIdentifier;
            conRecord.Source_of_Creation__c = 'JIT';
            insert conRecord;
        }
        else
            conRecord = conList[0];
    }

    /***************************************************************************************************** 
    Method Name:        handleJitForUAA
    @return  :          User
    Description:        UAA Just In Time provisioning
    Added By:           Accenture - SB
    Modified By:        Changes: 
    Accenture - SB      Associate the new Contact with "Registered User Account"
    ******************************************************************************************************/

    private User handleJitForUAA(Map<String, String> attributes, String federationIdentifier) {
        if(attributes.containsKey('origin') && ('uaa').equalsIgnoreCase(attributes.get('origin'))){
            handleContactForUAA(attributes, federationIdentifier);
            return handleUserForUAA(attributes, federationIdentifier);
        }
        return NULL;
    }

    global User createUser(Id samlSsoProviderId, Id communityId, Id portalId,
        String federationIdentifier, Map<String, String> attributes, String assertion) {
        return handleJitForUAA(attributes, federationIdentifier);
    }

    global void updateUser(Id userId, Id samlSsoProviderId, Id communityId, Id portalId,
        String federationIdentifier, Map<String, String> attributes, String assertion) {
    }
}