src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Best_Method_of_Contact__c</fullName>
        <description>This field is used to store Preferred method of contact</description>
        <label>Best Method of Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                    <isActive>false</isActive>
                    <label>Portal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Company__c</fullName>
        <label>Contact Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Selection2__c</fullName>
        <label>Product Selection</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Selection__c</fullName>
        <label>Product Selection</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cloud Foundry</fullName>
                </value>
                <value>
                    <fullName>MADlib</fullName>
                </value>
                <value>
                    <fullName>Pivotal App Suite</fullName>
                </value>
                <value>
                    <fullName>Pivotal Big Data Suite</fullName>
                </value>
                <value>
                    <fullName>Pivotal CF</fullName>
                </value>
                <value>
                    <fullName>Pivotal Chorus</fullName>
                </value>
                <value>
                    <fullName>Pivotal Data Dispatch</fullName>
                </value>
                <value>
                    <fullName>Pivotal Data Labs</fullName>
                </value>
                <value>
                    <fullName>Pivotal Data Tools</fullName>
                </value>
                <value>
                    <fullName>Pivotal DCA</fullName>
                </value>
                <value>
                    <fullName>Pivotal GemFire</fullName>
                </value>
                <value>
                    <fullName>Pivotal GPText</fullName>
                </value>
                <value>
                    <fullName>Pivotal Greenplum DB</fullName>
                </value>
                <value>
                    <fullName>Pivotal HD</fullName>
                </value>
                <value>
                    <fullName>Pivotal One</fullName>
                </value>
                <value>
                    <fullName>Pivotal RabbitMQ</fullName>
                </value>
                <value>
                    <fullName>Pivotal SQLFire</fullName>
                </value>
                <value>
                    <fullName>Pivotal tc Server</fullName>
                </value>
                <value>
                    <fullName>Pivotal Web Server</fullName>
                </value>
                <value>
                    <fullName>Redis</fullName>
                </value>
                <value>
                    <fullName>Spring</fullName>
                </value>
                <value>
                    <fullName>vFabric Suite</fullName>
                </value>
                <value>
                    <fullName>Hadoop</fullName>
                </value>
                <value>
                    <fullName>Containers</fullName>
                </value>
                <value>
                    <fullName>Big Data</fullName>
                </value>
                <value>
                    <fullName>Pharma</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TermsAndConditions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for Service Cloud Community...contacts should be selecting during registration.</description>
        <label>Terms &amp; Conditions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <defaultValue>"America/Los_Angeles"</defaultValue>
        <label>Time zone where you work</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pacific/Enderbury</fullName>
                </value>
                <value>
                    <fullName>Pacific/Tongatapu</fullName>
                </value>
                <value>
                    <fullName>Pacific/Chatham</fullName>
                </value>
                <value>
                    <fullName>Asia/Kamchatka</fullName>
                </value>
                <value>
                    <fullName>Pacific/Auckland</fullName>
                </value>
                <value>
                    <fullName>Pacific/Fiji</fullName>
                </value>
                <value>
                    <fullName>Pacific/Guadalcanal</fullName>
                </value>
                <value>
                    <fullName>Pacific/Norfolk</fullName>
                </value>
                <value>
                    <fullName>Australia/Lord_Howe</fullName>
                </value>
                <value>
                    <fullName>Australia/Brisbane</fullName>
                </value>
                <value>
                    <fullName>Australia/Sydney</fullName>
                </value>
                <value>
                    <fullName>Australia/Adelaide</fullName>
                </value>
                <value>
                    <fullName>Australia/Darwin</fullName>
                </value>
                <value>
                    <fullName>Asia/Seoul</fullName>
                </value>
                <value>
                    <fullName>Asia/Tokyo</fullName>
                </value>
                <value>
                    <fullName>Asia/Hong_Kong</fullName>
                </value>
                <value>
                    <fullName>Asia/Kuala_Lumpur</fullName>
                </value>
                <value>
                    <fullName>Asia/Manila</fullName>
                </value>
                <value>
                    <fullName>Asia/Shanghai</fullName>
                </value>
                <value>
                    <fullName>Asia/Singapore</fullName>
                </value>
                <value>
                    <fullName>Asia/Taipei</fullName>
                </value>
                <value>
                    <fullName>Australia/Perth</fullName>
                </value>
                <value>
                    <fullName>Asia/Bangkok</fullName>
                </value>
                <value>
                    <fullName>Asia/Ho_Chi_Minh</fullName>
                </value>
                <value>
                    <fullName>Asia/Jakarta</fullName>
                </value>
                <value>
                    <fullName>Asia/Rangoon</fullName>
                </value>
                <value>
                    <fullName>Asia/Dhaka</fullName>
                </value>
                <value>
                    <fullName>Asia/Kathmandu</fullName>
                </value>
                <value>
                    <fullName>Asia/Colombo</fullName>
                </value>
                <value>
                    <fullName>Asia/Kolkata</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/classes/ContactUpdateApexController_TC.cls
/*
*************************************************************************************************************
* Apex Class Name  : ContactUpdateApexController_TC
* Version          : 1.0
* Created Date     : 13 Mar 2018
* Function         : Class is used test ContactUpdateApexController - update Contact with field values 
					 coming from Login Flow
* Modification Log : 
*
* Developer                        Date                       Description
* ------------------------------------------------------------------------------------------------------------------
* Soham Banerjee	             13/03/2018            Test Class to test ContactUpdateApexController
* ------------------------------------------------------------------------------------------------------------------
************************************************************************************************************
*/
@isTest
private class ContactUpdateApexController_TC {
	
	@isTest static void test_method_one() {
		Test.startTest();
        TestDataUtil.dataValueMapCSData();
        Contact rCont = TestDataUtil.createPortalContact();
        System.assert(rCont !=null);
        System.assert(rCont.Name ==null, rCont.Name);
		List<String> strFieldValuesList = new List<String>();
		strFieldValuesList.add(rCont.Id);
		strFieldValuesList.add('Email');
		strFieldValuesList.add('Test Company');
		strFieldValuesList.add('9876543210');
		strFieldValuesList.add('Pivotal App Suite');
		strFieldValuesList.add('Pacific/Enderbury');
		strFieldValuesList.add('Specialist');
		strFieldValuesList.add('IN');

		List<String> parametersList = new List<String>();
		parametersList.add('Id=' + strFieldValuesList[0] + 
						   '~Best_Method_of_Contact__c=' + strFieldValuesList[1] + 
						   '~Company__c=' + strFieldValuesList[2] + 
						   '~Phone=' + strFieldValuesList[3] + 
						   '~Product_Selection2__c=' + strFieldValuesList[4] + 
						   '~TermsAndConditions__c=true' + 
						   '~Time_Zone__c=' + strFieldValuesList[5] + 
						   '~Title=' + strFieldValuesList[6] + 
						   '~MailingCountryCode=' + strFieldValuesList[7] +
       					   '~PCN=true' +
                          '~AlreadyL2=true');
		ContactUpdateApexController.updateContact(parametersList);
		Test.stopTest();
		/*System.assertEquals('Email', rCont.Best_Method_of_Contact__c);
		System.assertEquals('Test Company', rCont.Contact_Company__c);
		System.assertEquals('9876543210', rCont.Phone);
		System.assertEquals('Pivotal App Suite', rCont.Product_Selection__c);
		System.assertEquals(true, rCont.TermsAndConditions__c);
		System.assertEquals('Pacific/Enderbury', rCont.Time_Zone__c);
		System.assertEquals('Specialist', rCont.Title);
		System.assertEquals('IN', rCont.MailingCountryCode);*/
	}
}