src/objects/Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>Cause__c</fullName>
        <description>Cause of the exception</description>
        <label>Cause</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Source of exception – Apex class name</description>
        <label>Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LineNumber__c</fullName>
        <label>LineNumber</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logged_In_User__c</fullName>
        <label>Logged In User</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <label>StackTrace</label>
        <type>TextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ErrorLog.cls
/*******************************************************************************************************************
* Apex Class Name  : ErrorLog
* Version          : 1.0
* Function         : Class is used capture exception log and create a record for it.
* Modification Log :
*
* Developer                        Date                       Description
* ------------------------------------------------------------------------------------------------------------------
* Ranjithkumar Udhaya        10/11/2017               Utility Class to Capture exception log
* --------------------------------------------------------------------------------------------------------------------
*******************************************************************************************************************/
/***
Purpose : Utility Class to Capture exception log
***/
public without sharing class ErrorLog{  
/***
Method Name : CreateER
Purpose : Method is used to Create a error log record to capture the exception message
***/    
    public static void CreateER(Exception e){
      
        String loggedinUser = userinfo.getName();
        Exception_Log__c elog = new Exception_Log__c();
        elog.Cause__c = string.valueOf(e.getCause());
        elog.Class_Name__c = e.getStackTraceString().substringBefore(':');
        elog.Exception_Message__c = e.getMessage();
        elog.LineNumber__c = string.valueOf(e.getLineNumber());
        elog.StackTrace__c = e.getStackTraceString();
        elog.logged_in_user__c = loggedinUser;
        Database.insert(elog,false);
   
    }
}