src/objects/Foundations__c.object
<CustomObject>
    <fields>
        <fullName>Month_Consumption_Collected__c</fullName>
        <inlineHelpText>Please enter the Month the collected consumption data refers to. This field will purposefully go blank upon successful save.</inlineHelpText>
        <label>Month Consumption Collected</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
                <value>
                    <fullName>January</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Month_Consumption_Collected__c</fullName>
        <label>Previous Month Consumption Collected</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Foundations</label>
    <nameField>
        <label>Foundations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FoundationsHandler.cls
global class FoundationsHandler {

  public static Boolean hasAlreadyExecuted = false;

  @future
  public static void HandleFoundationUpdate(List<Id> recordIds) {
  

        if(checkRecursiveUtil.runOnce() || Test.isRunningTest()){
         
            List< Foundations__c > foundationsList = [Select Id, Month_Consumption_Collected__c, Previous_Month_Consumption_Collected__c from Foundations__c Where Id IN :recordIds];
            
            List<Foundations__c> foundationsUpdateList = new list<Foundations__c>();
            for( Foundations__c foundation : foundationsList ){
                if ( ! string.IsBlank(foundation.Month_Consumption_Collected__c)){
                    foundation.Previous_Month_Consumption_Collected__c = foundation.Month_Consumption_Collected__c;
                    foundation.Month_Consumption_Collected__c =null;
                    foundationsUpdateList.add(foundation);
                }
            
            }
            
            if(foundationsUpdateList.size()>0)
            {
                 update foundationsUpdateList;
            }
        
    }
  }
}