src/objects/Foundations__c.object
<CustomObject>
    <fields>
        <fullName>Account_FR__c</fullName>
        <description>Master Detail Lookup to Account Record for Foundations</description>
        <label>Account (FR)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Foundations</relationshipLabel>
        <relationshipName>Foundations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <description>Picklist of environment name types for foundations</description>
        <inlineHelpText>Please choose an environment name from the available list</inlineHelpText>
        <label>Environment</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Pre-Production</fullName>
                </value>
                <value>
                    <fullName>Non-Production</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>QA</fullName>
                </value>
                <value>
                    <fullName>Disaster Recovery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Month_Consumption_Collected__c</fullName>
        <inlineHelpText>Please enter the Month the collected consumption data refers to. This field will purposefully go blank upon successful save.</inlineHelpText>
        <label>Month Consumption Collected</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
                <value>
                    <fullName>January</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Foundations</label>
    <nameField>
        <label>Foundations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foundations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FoundationsTest.cls
@isTest
public class FoundationsTest {
    // Utility method that can be called by Apex tests to create price book entries.
    static testmethod void TestFoundation() {
        
         Account acc = TestDataUtil.createAccount();    
        
         Foundations__c foundation = new Foundations__c();
         foundation.Month_Consumption_Collected__c='February';
         foundation.Environment__c ='UAT';
         foundation.Account_FR__c = acc.id;
         insert foundation;
        
         test.StartTest();
         foundation.Month_Consumption_Collected__c='March';
         update foundation;
         test.StopTest();
        

         foundation.Month_Consumption_Collected__c='June';
         update foundation;

        

    }
    
}