src/objects/KnowledgeArticle__kav.object
<CustomObject>
    <fields>
        <fullName>Article_Author_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to User who authored the Knowledge Article.  May be a currently inactive legacy User.</description>
        <label>Article Author</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Knowledge_Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <description>2018 Service Cloud Implementation - KEEP This Product field.</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <inlineHelpText>What actions can the reader take to resolve or work around the described problem?</inlineHelpText>
        <label>Resolution</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Symptom__c</fullName>
        <description>Description of the symptoms or problem statement.</description>
        <inlineHelpText>Description of the symptoms or problem statement.</inlineHelpText>
        <label>Symptom</label>
        <length>100000</length>
        <type>Html</type>
    </fields>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge Article</label>
    <pluralLabel>Knowledge Articles</pluralLabel>
</CustomObject>

src/globalValueSets/Product.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>Alpine Chorus for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Concourse for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Hyper-Q for Pivotal Data Suite</fullName>
    </customValue>
    <customValue>
        <fullName>Datometry Workload Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PKS</fullName>
    </customValue>
    <customValue>
        <fullName>Gitlab Enterprise Plus for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Greenplum MapReduce</fullName>
    </customValue>
    <customValue>
        <fullName>ISS Knowtify for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>MADlib</fullName>
    </customValue>
    <customValue>
        <fullName>MySQL for Pivotal Cloud Foundry</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache HTTP Server</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Apache Tomcat</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Groovy &amp; Grails</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source PostgreSQL</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source RabbitMQ</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Redis</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source Spring.io</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source SpringXD</fullName>
    </customValue>
    <customValue>
        <fullName>OSS Support for Spring Cloud Data Flow</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Elastic Runtime Suite</fullName>
        <label>Pivotal Application Service (formerly Elastic Runtime)</label>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Cache</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Cloud Foundry Operations Manager v2</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Command Center</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal Data Dispatch</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire</fullName>
    </customValue>
    <customValue>
        <fullName>Pivotal GemFire for Pivotal Cloud Foundry</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

src/classes/FollowedArticleController_TC.cls
@isTest
Private class FollowedArticleController_TC {
    static testMethod  void  testgetFollowedAricles(){
        TestDataUtil.dataValueMapCSData();
        KnowledgeArticle__kav bf = new KnowledgeArticle__kav();
        bf.Title = 'Test Articles';
        bf.UrlName = 'TestArticles';
        bf.Symptom__c = 'Test Articles';
        bf.Resolution__c = 'Test Articles';
        bf.Product2__c  = 'Alpine Chorus for Pivotal Data Suite';
        bf.Article_Author_Lookup__c = UserInfo.getUserId();
        insert bf;
        System.assert(bf.Id!=null);
        String arId = [SELECT KnowledgeArticleId FROM KnowledgeArticle__kav WHERE Id = :bf.Id].KnowledgeArticleId;
        KbManagement.PublishingService.publishArticle(arId, true);
        
        List<EntitySubscription> lstEntSubs = new List<EntitySubscription>();
        EntitySubscription entSubs = new EntitySubscription();
        entSubs.SubscriberId = UserInfo.getUserId();
        entSubs.ParentId = arId; 
        insert entSubs;
        
        FollowedArticleController.getFollowedAricles();
        
    }
}