src/objects/PAC__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Date__c</fullName>
        <label>Assignment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration in Years</description>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>29</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>PACs</relationshipLabel>
        <relationshipName>PACs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                    <default>true</default>
                    <label>Unassigned</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PAC</label>
    <nameField>
        <displayFormat>PAC-{000000}</displayFormat>
        <label>PAC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PACs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PAC_Product_Map__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAC_Product__c</fullName>
        <label>PAC Product</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected ZProduct is Deleted</errorMessage>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>PAC Product Maps</relationshipLabel>
        <relationshipName>PAC_Product_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PAC Product Map</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>PAC Product Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAC Product Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PACHelper.cls
public with sharing class PACHelper {

    public static List<PAC__c> findPacByKeys(Set<String> uniqueKeys) {
        return [
                SELECT Key__c
                FROM PAC__c
                WHERE Key__c IN :uniqueKeys
        ];
    }

//    public static List<PAC__c> findPacByQuoteId(Id quoteId) {
//        return [
//                SELECT Quote__c, Assignment_Date__c, Status__c
//                FROM PAC__c
//                WHERE Quote__c = :quoteId
//        ];
//    }

    public static Set<String> findPacKeysByKeys(Set<String> uniqueKeys) {
        Set<String> existingKeys = new Set<String>();
        for (PAC__c pac : findPacByKeys(uniqueKeys)) {
            existingKeys.add(pac.Key__c.toUpperCase());
        }
        return existingKeys;
    }

//    public static List<PAC_Product_Map__c> findPacProductMap(Set<String> products) {
//        return [
//                SELECT PAC_Product__c, ZProduct__c
//                FROM PAC_Product_Map__c
//                WHERE PAC_Product__c IN :products
//                AND Active__c = TRUE
//        ];
//    }

//    public static Map<String, PAC_Product_Map__c> getProduct2ProductMap(Set<String> products) {
//        Map<String, PAC_Product_Map__c> resultMap = new Map<String, PAC_Product_Map__c>();
//        for (PAC_Product_Map__c mapEntry : findPacProductMap(products)) {
//            resultMap.put(mapEntry.PAC_Product__c, mapEntry);
//        }
//        return resultMap;
//    }

    /*public static List<PAC__c> findAvailableToAllocateByProduct(Set<String> products) {
        return [
                SELECT Quantity__c, Duration__c, Product__c
                FROM PAC__c
                WHERE Status__c = 'Unassigned'
                AND Product__c IN :products
                ORDER BY Quantity__c DESC, Duration__c DESC
        ];
    }*/

    public static List<PAC__c> findAvailableToAllocate() {
        return [
                SELECT Quantity__c, Duration__c, Product__c
                FROM PAC__c
                WHERE Status__c = 'Unassigned'
                ORDER BY Quantity__c DESC, Duration__c DESC
        ];
    }

    public static String getPACGroupingFieldValue(PAC__c pac){
        return pac.Quantity__c + '_' + pac.Duration__c;
    }

    public class PACWrapper {
        public PAC__c pac {get; private set;}
        public Boolean duplicate {get; set;}

        public PACWrapper(PAC__c pac, Boolean duplicate) {
            this.pac = pac;
            this.duplicate = duplicate;
        }
    }
}