src/objects/PAC__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration in Years</description>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>29</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PAC</label>
    <nameField>
        <displayFormat>PAC-{000000}</displayFormat>
        <label>PAC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PACs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPACBuilder.cls
@IsTest
public with sharing class TestPACBuilder {

    private PAC__c pac;

    public TestPACBuilder() {
        pac = new PAC__c();
    }

    public TestPACBuilder withCode(String code) {
        this.pac.Code__c = code;
        return this;
    }

    public TestPACBuilder withProduct(String product) {
        this.pac.Product__c = product;
        return this;
    }

    public TestPACBuilder withDuration(Decimal duration) {
        this.pac.Duration__c = duration;
        return this;
    }

    public TestPACBuilder withQuantity(Decimal quantity) {
        this.pac.Quantity__c = quantity;
        return this;
    }

    public TestPACBuilder withKey(String key) {
        this.pac.Key__c = key;
        return this;
    }

    public PAC__c buildWithoutSave() {
        return pac;
    }

    public PAC__c build() {
        buildWithoutSave();
        insert pac;
        return pac;
    }

    public PAC__c buildWithoutSaveAndClone() {
        PAC__c tmp = buildWithoutSave();
        this.pac = pac.clone();
        return tmp;
    }
}