src/objects/PAC__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>PACs</relationshipLabel>
        <relationshipName>PACs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>29</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>PACs</relationshipLabel>
        <relationshipName>PACs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Period__c</fullName>
        <formula>(RIGHT(TEXT(Subscription_Period_Start_Date__c), 2) + "-" + 
CASE( 
RIGHT(LEFT(TEXT(Subscription_Period_Start_Date__c),7),2), 
"01", "Jan", 
"02", "Feb", 
"03", "Mar", 
"04", "Apr", 
"05", "May", 
"06", "Jun", 
"07", "Jul", 
"08", "Aug", 
"09", "Sep", 
"10", "Oct", 
"11", "Nov", 
"12", "Dec", 
"None" 
) 
+ "-" + LEFT(TEXT(Subscription_Period_Start_Date__c) , 4) 
+ " to " + 
RIGHT( TEXT(Subscription_Period_End_Date__c), 2) + "-" + 
CASE( 
RIGHT(LEFT(TEXT(Subscription_Period_End_Date__c),7),2), 
"01", "Jan", 
"02", "Feb", 
"03", "Mar", 
"04", "Apr", 
"05", "May", 
"06", "Jun", 
"07", "Jul", 
"08", "Aug", 
"09", "Sep", 
"10", "Oct", 
"11", "Nov", 
"12", "Dec", 
"None" 
) 
+ "-" + LEFT(TEXT(Subscription_Period_End_Date__c) , 4) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription Period</label>
        <type>Text</type>
    </fields>
    <label>PAC</label>
    <nameField>
        <displayFormat>PAC-{000000}</displayFormat>
        <label>PAC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PACs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PACEmailTableController.cls
/**
 * Created by klukawski on 9/7/18.
 */

global with sharing class PACEmailTableController {
    public Id quoteId {get; set{
        System.debug(value);
        quoteId = value;
        pacs = new List<PAC__c>([
                SELECT Key__c, Quantity__c, Product__c, Subscription_Period__c, Assigned_Product2__c,
                        Assigned_Product2__r.Name
                FROM PAC__c
                WHERE Quote__c = :value
                ORDER BY Assigned_Product2__c DESC, Quantity__c DESC
        ]);
        List<Id> prods = new List<Id>();
        for(PAC__c pac: pacs){
            if(!prods.contains(pac.Assigned_Product2__c)){
                prods.add(pac.Assigned_Product2__c);
            }
        }
        List<zqu__ProductRatePlanCharge__c> uomObjects = [
                SELECT UOM_Without_Unit_Quantity__c, zqu__ProductRatePlan__r.zqu__Product__c
                FROM zqu__ProductRatePlanCharge__c
                WHERE zqu__ProductRatePlan__r.zqu__Product__c IN :prods
        ];
        UOMs = new Map<Id, String>();
        for(zqu__ProductRatePlanCharge__c prpc: uomObjects){
            UOMs.put(prpc.zqu__ProductRatePlan__r.zqu__Product__c, prpc.UOM_Without_Unit_Quantity__c);
        }
    }}
    public List<PAC__c> pacs {get;set;}
    public Map<Id, String> UOMs {get; set;}
    public Boolean renderPACs {
        get {
            System.debug('getter');
            return (!pacs.isEmpty() && quoteId != null);
        }
        set;
    }
}