src/objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Role_Instance__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Per_Role__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hours Per Role</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <formula>Total_Hours__c * Hourly_rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Rate Plan Charge</label>
        <referenceTo>zqu__QuoteRatePlanCharge__c</referenceTo>
        <relationshipLabel>Role Instance</relationshipLabel>
        <relationshipName>Role_Instance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Role Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <formula>Role_Quantity__c * Hours_Per_Role__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Role Instance</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Instance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoleHelper.cls
public with sharing class RoleHelper {
    public static final String STATUS_ROLE_MAPPING_ACTIVE   = 'Active';
    public static final String STATUS_ROLE_MAPPING_INACTIVE = 'Inactive';

    public static List<Role_Instance__c> findRoleInstancesByQRPCId(Id qrpcId) {
        return [
                SELECT id, Name, Total_Hours__c, Role_Quantity__c, Hours_Per_Role__c, Hourly_rate__c, List_Price__c
                FROM Role_Instance__c
                WHERE Quote_Rate_Plan_Charge__c = :qrpcId
        ];
    }

    public static Set<String> findRoleNamesAssignedToQRPCId(Id qrpcId) {
        Set<String> roleNames = new Set<String>();
        for (Role_Instance__c instance : findRoleInstancesByQRPCId(qrpcId)) {
            roleNames.add(instance.Name);
        }
        return roleNames;
    }

    public static List<Role__c> findAllRoles() {
        return [SELECT Name, Hourly_Rate__c, CreatedDate, CreatedBy.Name FROM Role__c];
    }

    public static List<Role__c> findRolesAssignableToCustomQRPC(Id qrpcId) {
        Set<String> assignedRoleNames = findRoleNamesAssignedToQRPCId(qrpcId);
        String currencyCode = getCurrency(qrpcId);
        return [
                SELECT Name, Hourly_Rate__c, CreatedDate, CreatedBy.Name, CurrencyIsoCode
                FROM Role__c
                WHERE Name NOT IN :assignedRoleNames
                AND CurrencyIsoCode = :currencyCode
        ];
    }

    public static Boolean isAddingRoleAvailable(zqu__QuoteRatePlanCharge__c quoteRatePlanCharge) {
        return true;
//        return quoteRatePlanCharge.Name.containsIgnoreCase('custom');
//                String.isBlank(quoteRatePlanCharge.Listed_Price__c) ||
//                Decimal.valueOf(quoteRatePlanCharge.Listed_Price__c) == 0;
    }

    private static String getCurrency(Id qrpcId) {
        zqu__QuoteRatePlanCharge__c qrpc = [
                SELECT Id, zqu__QuoteRatePlan__r.zqu__Quote__r.zqu__Currency__c
                FROM zqu__QuoteRatePlanCharge__c
                WHERE Id = :qrpcId
        ];
        return qrpc.zqu__QuoteRatePlan__r.zqu__Quote__r.zqu__Currency__c;
    }
}