src/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Role_to_PRPC_Map__c.object
<CustomObject>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <label>Product Rate Plan Charge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ProductRatePlanCharge__c.zqu__Deleted__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Role to PRPC Map</relationshipLabel>
        <relationshipName>Role_to_PRPC_Map</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Role to PRPC Map</relationshipLabel>
        <relationshipName>Role_to_PRPC_Map</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Role to PRPC Map</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>Role to PRPC Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role to PRPC Map</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestRoleToPrpcMapBuilder.cls
@IsTest
public with sharing class TestRoleToPrpcMapBuilder {

    private Role_to_PRPC_Map__c roleMap;

    public TestRoleToPrpcMapBuilder() {
        this.roleMap = new Role_to_PRPC_Map__c();
    }

    public TestRoleToPrpcMapBuilder withRoleId(Id roleId) {
        this.roleMap.Role__c = roleId;
        return this;
    }

    public TestRoleToPrpcMapBuilder withPrpc(Id prpcId) {
        this.roleMap.Product_Rate_Plan_Charge__c = prpcId;
        return this;
    }

    public TestRoleToPrpcMapBuilder withStatus(String status) {
        this.roleMap.Status__c = status;
        return this;
    }

    public Role_to_PRPC_Map__c buildWithoutSave() {
        if (roleMap.Status__c == null) {
            roleMap.Status__c = RoleHelper.STATUS_ROLE_MAPPING_ACTIVE;
        }
        return roleMap;
    }

    public Role_to_PRPC_Map__c build() {
        insert roleMap;
        return roleMap;
    }

    public Role_to_PRPC_Map__c buildMultipleWithoutSave() {
        Role_to_PRPC_Map__c tmp = buildWithoutSave();
        this.roleMap = roleMap.clone();
        return tmp;
    }

    public static List<Role_to_PRPC_Map__c> assignRolesToPrpc(Id prpcId, List<Role__c> roles) {
        List<Role_to_PRPC_Map__c> mappings = new List<Role_to_PRPC_Map__c>();
        TestRoleToPrpcMapBuilder builder = new TestRoleToPrpcMapBuilder()
            .withPrpc(prpcId);
        for (Role__c role : roles) {
            mappings.add(builder
                .withRoleId(role.Id)
                .buildMultipleWithoutSave());
        }
        return mappings;
    }
}