src/objects/Role_Instance__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Per_Role__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hours Per Role</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Rate Plan Charge</label>
        <referenceTo>zqu__QuoteRatePlanCharge__c</referenceTo>
        <relationshipLabel>Role Instance</relationshipLabel>
        <relationshipName>Role_Instance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Role Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <formula>Role_Quantity__c * Hours_Per_Role__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Role Instance</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Instance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoleInstanceComponentController.cls
public class RoleInstanceComponentController{
    public final zqu__QuoteRatePlanCharge__c quoteRatePlanCharge {get; set;}
    public Boolean editMode {get; set;}
    public Id instanceIdEdit {get; set;}

    public List<Role_Instance__c> instances{get; private set;}

    public RoleInstanceComponentController(ApexPages.StandardController controller){
        quoteRatePlanCharge = (zqu__QuoteRatePlanCharge__c)controller.getRecord();
        editMode = true;
        instances = [
                SELECT Name, Role_Quantity__c, Hourly_rate__c, Hours_Per_Role__c, Total_Hours__c
                FROM Role_Instance__c
                WHERE Quote_Rate_Plan_Charge__c = :quoteRatePlanCharge.Id
        ];
    }

    public PageReference saveAndCalculate(){
        System.debug('RoleInstanceComponentController::saveAndCalculate instances: ' + instances);
//        editMode = false;
        update instances;
        return null;
    }

    public PageReference editRow() {
        System.debug('RoleInstanceComponentController::editRow instanceIdEdit: ' +instanceIdEdit);
        editMode = true;
        return null;
    }

    public Id getQRPCId() {
        return quoteRatePlanCharge.Id;
    }

    public Boolean getIsCustomCharge() {
        return RoleHelper.isAddingRoleAvailable(quoteRatePlanCharge);
    }

    public boolean displayPopup {get; set;}

    public void closePopup() {
        displayPopup = false;
    }
    public void showPopup() {
        displayPopup = true;
    }

    public Boolean getRenderPage() {
        return !instances.isEmpty() || getIsCustomCharge();
    }
}