src/objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Role_Instance__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Rate Plan Charge</label>
        <referenceTo>zqu__QuoteRatePlanCharge__c</referenceTo>
        <relationshipLabel>Role Instance</relationshipLabel>
        <relationshipName>Role_Instance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Role Instance</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Instance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Role_to_PRPC_Map__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Role to PRPC Map</relationshipLabel>
        <relationshipName>Role_to_PRPC_Map</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Role to PRPC Map</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>Role to PRPC Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role to PRPC Map</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RoleToRoleInstanceConverter.cls
public with sharing class RoleToRoleInstanceConverter {
    private Role__c role;
    private Id qrpcId;
    private Role_Instance__c roleInstance;

    public RoleToRoleInstanceConverter() {
    }

    public RoleToRoleInstanceConverter withRole(Role__c role) {
        this.role = role;
        return this;
    }

    public RoleToRoleInstanceConverter withQuoteRPCId(Id qrpcId) {
        this.qrpcId = qrpcId;
        return this;
    }

    public Role_Instance__c convert() {
        roleInstance = new Role_Instance__c(
                Name = role.Name,
                Hourly_rate__c = role.Hourly_rate__c,
                Quote_Rate_Plan_Charge__c = qrpcId,
                CurrencyIsoCode = role.CurrencyIsoCode
        );
        return roleInstance;
    }

    public static List<Role_Instance__c> convert(List<Role_to_PRPC_Map__c> rolesMap, Id quoteRPCId) {
        RoleToRoleInstanceConverter converter = new RoleToRoleInstanceConverter()
                .withQuoteRPCId(quoteRPCId);
        List<Role_Instance__c> instances = new List<Role_Instance__c>();
        for (Role_to_PRPC_Map__c mapping : rolesMap) {
            if (null != mapping.Role__r) {
                instances.add(converter.withRole(mapping.Role__r).convert());
            }
        }
        return instances;
    }

    public static Role_Instance__c convert(Role__c role, Id quoteRPCId) {
        return new RoleToRoleInstanceConverter()
                .withRole(role)
                .withQuoteRPCId(quoteRPCId)
                .convert();
    }
}