src/objects/Role_Instance__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Per_Role__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hours Per Role</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <formula>Total_Hours__c * Hourly_rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Rate Plan Charge</label>
        <referenceTo>zqu__QuoteRatePlanCharge__c</referenceTo>
        <relationshipLabel>Role Instance</relationshipLabel>
        <relationshipName>Role_Instance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Role Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <formula>Role_Quantity__c * Hours_Per_Role__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Role Instance</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Instance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoleInstancesOnQuoteRatePlanController.cls
public with sharing class RoleInstancesOnQuoteRatePlanController {
    private Id qrpId;
    public List<Role_Instance__c> instances {get; set;}

    public RoleInstancesOnQuoteRatePlanController(ApexPages.StandardController stdController) {
        qrpId = stdController.getRecord().Id;
        instances = [
                SELECT id, Name, List_Price__c, Hourly_rate__c, Hours_Per_Role__c, Role_Quantity__c, Total_Hours__c
                FROM Role_Instance__c WHERE Quote_Rate_Plan_Charge__r.zqu__QuoteRatePlan__c = :qrpId];
    }
//
//    public RoleInstancesOnQuoteRatePlanController() {
//        Id quoteId = ApexPages.currentPage().getParameters().get('quoteId');
//        instances = [SELECT id, Name, List_Price__c, Hourly_rate__c, Hours_Per_Role__c, Role_Quantity__c, Total_Hours__c
//                FROM Role_Instance__c WHERE Quote_Rate_Plan_Charge__r.zqu__QuoteRatePlan__r.zqu__Quote__c = :quoteId];
//    }
}