src/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Success_Team__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Support Success Teams</relationshipLabel>
        <relationshipName>Success_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Choose "Case Notification" to be notified when a Case is created for this Account. 
Choose "Case Team" to be emailed updates for all open Cases under this Account.</description>
        <inlineHelpText>Choose "Case Notification" to be notified when a Case is created for this Account. 
Choose "Case Team" to be emailed updates for all open Cases under this Account.</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Case Notification</fullName>
                </value>
                <value>
                    <fullName>New Case Notification &amp; Case Team</fullName>
                </value>
                <value>
                    <fullName>Case Notification</fullName>
                    <isActive>false</isActive>
                    <label>Case Notification</label>
                </value>
                <value>
                    <fullName>Case Notification &amp; Case Team</fullName>
                    <isActive>false</isActive>
                    <label>Case Notification &amp; Case Team</label>
                </value>
                <value>
                    <fullName>Case Team</fullName>
                    <isActive>false</isActive>
                    <label>Case Team</label>
                </value>
                <value>
                    <fullName>New Case Team</fullName>
                    <isActive>false</isActive>
                    <label>New Case Team</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only Standard and Customer Portal User can be on a Success Team</errorMessage>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Customer Portal User, Customer Portal Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Customer Success Role for Strategic Accounts to trigger automation of Case Notifications or adding tot the Case Team.</description>
    <label>Support Success Team</label>
    <nameField>
        <displayFormat>ST{000000}</displayFormat>
        <label>Success Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Success Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PreventDuplicateSuccessTeamMemberTest.cls
@isTest
private class PreventDuplicateSuccessTeamMemberTest {
      @isTest
      private static void testSwitchAffectedSalesforceUser() {
    
        Account acc = new Account();
        acc.Name ='Test';
    
        Success_Team__c successTeam = new Success_Team__c();
        
        successTeam.User__c = UserInfo.getUserId();
        successTeam.Role__c ='New Case Notification';
    
        Test.startTest();
        insert acc;
        successTeam.Account__c=acc.Id;
        insert successTeam;
    
        Test.stopTest();
    
        
        list<Success_Team__c> newsuccessTeam = [SELECT Id, User__c, Role__c FROM Success_Team__c WHERE User__c = :UserInfo.getUserId() AND Account__c = :acc.Id];
        
        System.assertEquals(1,newsuccessTeam.size());
     }
}