src/objects/Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Success_Team__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Support Success Teams</relationshipLabel>
        <relationshipName>Success_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Choose "Case Notification" to be notified when a Case is created for this Account. 
Choose "Case Team" to be emailed updates for all open Cases under this Account.</description>
        <inlineHelpText>Choose "Case Notification" to be notified when a Case is created for this Account. 
Choose "Case Team" to be emailed updates for all open Cases under this Account.</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Case Notification</fullName>
                </value>
                <value>
                    <fullName>New Case Notification &amp; Case Team</fullName>
                </value>
                <value>
                    <fullName>Case Notification</fullName>
                    <isActive>false</isActive>
                    <label>Case Notification</label>
                </value>
                <value>
                    <fullName>Case Notification &amp; Case Team</fullName>
                    <isActive>false</isActive>
                    <label>Case Notification &amp; Case Team</label>
                </value>
                <value>
                    <fullName>Case Team</fullName>
                    <isActive>false</isActive>
                    <label>Case Team</label>
                </value>
                <value>
                    <fullName>New Case Team</fullName>
                    <isActive>false</isActive>
                    <label>New Case Team</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only Standard and Customer Portal User can be on a Success Team</errorMessage>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Customer Portal User, Customer Portal Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Customer Success Role for Strategic Accounts to trigger automation of Case Notifications or adding tot the Case Team.</description>
    <label>Support Success Team</label>
    <nameField>
        <displayFormat>ST{000000}</displayFormat>
        <label>Success Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Success Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendEmailToSuccessTeam_Test.cls
@isTest(seeAllData=false)
public class SendEmailToSuccessTeam_Test{

    
    static void SetupCustomSettingData(){
        TestDataUtil.dataValueMapCSData();
    }    
    
    
   static testmethod void test(){
        SetupCustomSettingData();
       
        profile p =[select id , name from profile where name='system administrator'];
        user u = createTestUser(p.id,'Dwayne','Johnson');
        
        account acc = new account();
        acc.name = 'test Account';

        insert acc; 
 
        contact con = new contact();
        con.FirstName = 'John';
        con.LastName = 'Wood';
        con.AccountId = acc.id;

        insert con;        
        
        
        list<Success_team__C> successTeamLst =  new list<Success_Team__c>();
        
        for(integer i=0; i<2; i++){
            Success_Team__c successTeam =  new Success_Team__c();
            successTeam.Role__c = 'New Case Notification';
            successTeam.user__c = u.id ;
            successTeam.account__c = acc.id;
            successTeamLst.add(successTeam);
        }
        insert successTeamLst;
        
        list<case>caseLst =  new list<case>();
        for(integer i = 0; i<2; i++){
            case c= new case();
            c.accountId = acc.id;
            c.contactid = con.id;
            c.Status ='New';
            c.Origin = 'Phone';
            caseLst.add(c);
        }
        insert caseLst;
       
       
        Case cse = [select id from case limit 1];
       
        SendEmailToSuccessTeam.InvocableVariables invocableclass = new SendEmailToSuccessTeam.InvocableVariables();
        invocableclass.caseId = cse.id;
        invocableclass.templateName='';
        list<SendEmailToSuccessTeam.InvocableVariables> invocableclassList = new list<SendEmailToSuccessTeam.InvocableVariables>();
        invocableclassList.add(invocableclass);
        SendEmailToSuccessTeam sendemailST = new SendEmailToSuccessTeam();
        SendEmailToSuccessTeam.SendSuccessTeamEmailAlert(invocableclassList);
            
    }
    
    
    
    public static user createTestUser(string pId, string fName, string lName){
        
        string orgId = userinfo.getOrganizationId();
        string dateString = string.valueOf(datetime.now()).replace(' ','').replace(':','').replace('-','');
        
        integer randomValue = integer.valueOf(math.rint(math.random()*1000000));
        string uniqueName = orgId+datestring+RandomValue;
        
        user u = new user(firstName = fName,
                          lastName = lName,
                          Email = uniqueName + '@test' + orgId + '.org',
                          userName = uniqueName + '@test' + orgId + '.org',
                          EmailEncodingKey = 'ISO-8859-1',
                          alias = uniqueName.substring(18,23),
                          TimeZoneSidKey = 'America/Los_Angeles',
                          LocaleSidKey = 'en_US',
                          LanguageLocaleKey = 'en_US',
                          profileId = pId
                        );
        insert u;
         
        return u;
    }



}