src/objects/Zuora_New_Subscription_Notification__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Zuora New Subscription Notification</label>
    <nameField>
        <label>SubscriptionID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zuora New Subscription Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraNewSubscription.cls
/**
 * Created by klukawski on 1/25/18.
 */
@RestResource(urlMapping='/ZuoraNewSubscription')
global class ZuoraNewSubscription {
    @HttpPost
    global static String receiveNewSubscriptionNotification(String SubscriptionID, String StartDate, String EndDate) {
        Zuora_New_Subscription_Notification__c notif = new Zuora_New_Subscription_Notification__c(Name = SubscriptionID, StartDate__c = StartDate, EndDate__c = EndDate);
        insert notif;
        ZuoraRevenueSplitHelper.sendNewSubscriptionCallouts(new List<Id>{notif.Id});
        return 'Success';
    }
}