src/objects/Zuora_Amendment_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Zuora Amendment Notification</label>
    <nameField>
        <label>Amendment Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zuora Amendment Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraSubscriptionRenewal.cls
@RestResource(urlMapping='/ZuoraSubscriptionRenewal')
global class ZuoraSubscriptionRenewal{
    @HttpPost
    global static String receiveSubscriptionRenewalNotification(String AmendmentID) {
        Zuora_Amendment_Notification__c notif = new Zuora_Amendment_Notification__c(Name=AmendmentID, Type__c = 'Renewal');
        upsert notif;
        ZuoraRevenueSplitHelper.sendAmendmentCallouts(new List<Id>{notif.Id});
        return 'Success';
    }
}